const composition: Array<{
    id: string,
    isDecomposable: boolean,
    strokeCount: number | string[],
    hanzi: string,
    composition: string[]
}> = [{ "id": "D3", "isDecomposable": false, "strokeCount": 1, "hanzi": "五", "composition": ["＊一"] },
{ "id": "D4", "isDecomposable": false, "strokeCount": 3, "hanzi": "人", "composition": ["＊大"] },
{ "id": "D5", "isDecomposable": false, "strokeCount": 2, "hanzi": "之", "composition": ["＊人"] },
{ "id": "D6", "isDecomposable": false, "strokeCount": 2, "hanzi": "上", "composition": ["⿱一五", "＊丄"] },
{ "id": "D7", "isDecomposable": false, "strokeCount": 3, "hanzi": "手", "composition": ["＊屮"] },
{ "id": "D8", "isDecomposable": false, "strokeCount": 1, "hanzi": "一", "composition": ["＊丨", "＊〡"] },
{ "id": "D9", "isDecomposable": false, "strokeCount": 3.6, "hanzi": "足", "composition": ["＊廿"] },
{ "id": "D10", "isDecomposable": false, "strokeCount": 2, "hanzi": "閉", "composition": ["＊𠆢"] },
{ "id": "D11", "isDecomposable": false, "strokeCount": 1, "hanzi": "無", "composition": ["＊丶"] },
{ "id": "D12", "isDecomposable": true, "strokeCount": ["D3", "D3"], "hanzi": "処", "composition": ["⿱五五", "＊二", "＊ニ"] },
{ "id": "D13", "isDecomposable": false, "strokeCount": 1, "hanzi": "少", "composition": ["＊丿"] },
{ "id": "D14", "isDecomposable": false, "strokeCount": 5, "hanzi": "心", "composition": ["⿻再人"] },
{ "id": "D15", "isDecomposable": true, "strokeCount": ["D5", "D5"], "hanzi": "水", "composition": ["⿰之之", "＊ㅆ", "＊从"] },
{ "id": "D16", "isDecomposable": false, "strokeCount": 3, "hanzi": "口", "composition": ["＊口", "＊ロ"] },
{ "id": "D17", "isDecomposable": false, "strokeCount": 4, "hanzi": "糸", "composition": ["⿳五再五", "＊ㅍ"] },
{ "id": "D18", "isDecomposable": false, "strokeCount": 2, "hanzi": "物", "composition": ["＊マ"] },
{ "id": "D19", "isDecomposable": false, "strokeCount": 3, "hanzi": "声", "composition": ["＊万"] },
{ "id": "D20", "isDecomposable": false, "strokeCount": 5, "hanzi": "日", "composition": ["⿴口六", "＊田"] },
{ "id": "D21", "isDecomposable": false, "strokeCount": 4, "hanzi": "言", "composition": ["⿴口五", "＊日", "＊曰"] },
{ "id": "D22", "isDecomposable": false, "strokeCount": 2, "hanzi": "四", "composition": ["＊メ", "＊〤"] },
{ "id": "D23", "isDecomposable": false, "strokeCount": 3, "hanzi": "筆", "composition": ["＊巾"] },
{ "id": "D24", "isDecomposable": true, "strokeCount": ["D4", "D4"], "hanzi": "等", "composition": ["⿰人人"] },
{ "id": "D25", "isDecomposable": true, "strokeCount": ["D13", "D4"], "hanzi": "兵", "composition": ["⿰少人"] },
{ "id": "D26", "isDecomposable": false, "strokeCount": 3, "hanzi": "火", "composition": ["⿶四無", "＊义"] },
{ "id": "D27", "isDecomposable": false, "strokeCount": 3, "hanzi": "大", "composition": ["⿱六五", "＊土", "＊士"] },
{ "id": "D28", "isDecomposable": false, "strokeCount": 3, "hanzi": "耒", "composition": ["⿻門五"] },
{ "id": "D29", "isDecomposable": false, "strokeCount": 3, "hanzi": "光", "composition": ["⿻再＊亅"] },
{ "id": "D30", "isDecomposable": false, "strokeCount": 2, "hanzi": "己", "composition": ["＊ム", "＊厶"] },
{ "id": "D31", "isDecomposable": false, "strokeCount": 2, "hanzi": "下", "composition": ["⿱五一", "＊丅"] },
{ "id": "D32", "isDecomposable": false, "strokeCount": 5, "hanzi": "輪", "composition": ["＊毌"] },
{ "id": "D33", "isDecomposable": false, "strokeCount": 2, "hanzi": "衣", "composition": ["＊卩"] },
{ "id": "D34", "isDecomposable": false, "strokeCount": 2, "hanzi": "天", "composition": ["＊𠘨"] },
{ "id": "D35", "isDecomposable": false, "strokeCount": 2, "hanzi": "包", "composition": ["＊凵"] },
{ "id": "D36", "isDecomposable": false, "strokeCount": 3, "hanzi": "力", "composition": ["⿱五⿰少十"] },
{ "id": "D37", "isDecomposable": false, "strokeCount": 2, "hanzi": "連", "composition": ["⿹＊フ神"] },
{ "id": "D38", "isDecomposable": false, "strokeCount": 4, "hanzi": "筒", "composition": ["＊ㅒ"] },
{ "id": "D39", "isDecomposable": false, "strokeCount": 4, "hanzi": "直", "composition": ["＊丰"] },
{ "id": "D40", "isDecomposable": true, "strokeCount": ["D10", "D29"], "hanzi": "闇", "composition": ["⿱閉光"] },
{ "id": "D46", "isDecomposable": true, "strokeCount": ["D4", "D30"], "hanzi": "我", "composition": ["⿰人己", "⿺人己"] },
{ "id": "D47", "isDecomposable": true, "strokeCount": ["D4", "D18"], "hanzi": "汝", "composition": ["⿰人物", "⿺人物"] },
{ "id": "D48", "isDecomposable": true, "strokeCount": ["D30", "D16"], "hanzi": "此", "composition": ["⿱己口"] },
{ "id": "D49", "isDecomposable": true, "strokeCount": ["D18", "D16"], "hanzi": "其", "composition": ["⿱物口"] },
{ "id": "D50", "isDecomposable": true, "strokeCount": ["D14", "D11"], "hanzi": "何", "composition": ["⿵心無"] },
{ "id": "D51", "isDecomposable": true, "strokeCount": ["D16", "D18"], "hanzi": "全", "composition": ["⿴口物"] },
{ "id": "D52", "isDecomposable": true, "strokeCount": ["D18", "D30"], "hanzi": "互", "composition": ["⿱物己"] },
{ "id": "D53", "isDecomposable": true, "strokeCount": ["D20", "D9"], "hanzi": "時", "composition": ["⿱日足"] },
{ "id": "D54", "isDecomposable": true, "strokeCount": ["D21", "D6"], "hanzi": "故", "composition": ["⿱言上"] },
{ "id": "D55", "isDecomposable": true, "strokeCount": ["D7", "D7"], "hanzi": "術", "composition": ["⿰手手", "＊艸"] },
{ "id": "D56", "isDecomposable": true, "strokeCount": ["D23", "D12"], "hanzi": "書", "composition": ["⿱筆処"] },
{ "id": "D57", "isDecomposable": true, "strokeCount": ["D23", "D15"], "hanzi": "墨", "composition": ["⿰筆水"] },
{ "id": "D58", "isDecomposable": true, "strokeCount": ["D21", "D21"], "hanzi": "論", "composition": ["⿱言言"] },
{ "id": "D59", "isDecomposable": true, "strokeCount": ["D23", "D33"], "hanzi": "紙", "composition": ["⿰筆衣"] },
{ "id": "D60", "isDecomposable": true, "strokeCount": ["D22", "D4"], "hanzi": "頭", "composition": ["⿱四人"] },
{ "id": "D61", "isDecomposable": true, "strokeCount": ["D4", "D16"], "hanzi": "果", "composition": ["⿱人口"] },
{ "id": "D62", "isDecomposable": true, "strokeCount": ["D10", "D3"], "hanzi": "満", "composition": ["⿱閉五"] },
{ "id": "D63", "isDecomposable": true, "strokeCount": ["D6", "D33"], "hanzi": "清", "composition": ["⿱上衣"] },
{ "id": "D64", "isDecomposable": true, "strokeCount": ["D30", "D24"], "hanzi": "牌", "composition": ["⿱己等"] },
{ "id": "D65", "isDecomposable": true, "strokeCount": ["D18", "D24"], "hanzi": "豊", "composition": ["⿱物等"] },
{ "id": "D66", "isDecomposable": true, "strokeCount": ["D10", "D6"], "hanzi": "家", "composition": ["⿱閉上", "＊소"] },
{ "id": "D67", "isDecomposable": true, "strokeCount": ["D6", "D14"], "hanzi": "善", "composition": ["⿱上心"] },
{ "id": "D68", "isDecomposable": true, "strokeCount": ["D21", "D67"], "hanzi": "認", "composition": ["⿰言善"] },
{ "id": "D69", "isDecomposable": true, "strokeCount": ["D9", "D40"], "hanzi": "寝", "composition": ["⿰足闇"] },
{ "id": "D70", "isDecomposable": true, "strokeCount": ["D10", "D30"], "hanzi": "覆", "composition": ["⿱閉己"] },
{ "id": "D71", "isDecomposable": true, "strokeCount": ["D17", "D19"], "hanzi": "琴", "composition": ["⿰糸声"] },
{ "id": "D72", "isDecomposable": true, "strokeCount": ["D6", "D53"], "hanzi": "古", "composition": ["⿱上時"] },
{ "id": "D73", "isDecomposable": true, "strokeCount": ["D3", "D7"], "hanzi": "撃", "composition": ["⿱五手"] },
{ "id": "D74", "isDecomposable": true, "strokeCount": ["D9", "D9"], "hanzi": "行", "composition": ["⿱足足"] },
{ "id": "D75", "isDecomposable": true, "strokeCount": ["D16", "D4"], "hanzi": "囲", "composition": ["⿴口人", "＊因"] },
{ "id": "D76", "isDecomposable": true, "strokeCount": ["D21", "D24"], "hanzi": "党", "composition": ["⿱言等"] },
{ "id": "D77", "isDecomposable": true, "strokeCount": ["D9", "D67"], "hanzi": "笑", "composition": ["⿰足善"] },
{ "id": "D78", "isDecomposable": true, "strokeCount": ["D25", "D25"], "hanzi": "戦", "composition": ["⿰兵兵"] },
{ "id": "D79", "isDecomposable": true, "strokeCount": ["D19", "D11"], "hanzi": "静", "composition": ["⿻声無", "⿱五⿰四＊𠃌"] },
{ "id": "D80", "isDecomposable": true, "strokeCount": ["D3", "D12"], "hanzi": "層", "composition": ["⿱五処"] },
{ "id": "D81", "isDecomposable": true, "strokeCount": ["D14", "D19"], "hanzi": "噫", "composition": ["⿰心声"] },
{ "id": "D82", "isDecomposable": true, "strokeCount": ["D23", "D17"], "hanzi": "律", "composition": ["⿰筆糸"] },
{ "id": "D83", "isDecomposable": true, "strokeCount": ["D24", "D3"], "hanzi": "集", "composition": ["⿱等五"] },
{ "id": "D84", "isDecomposable": true, "strokeCount": ["D20", "D29"], "hanzi": "輝", "composition": ["⿱日光"] },
{ "id": "D85", "isDecomposable": true, "strokeCount": ["D20", "D3"], "hanzi": "始", "composition": ["⿱日五"] },
{ "id": "D86", "isDecomposable": true, "strokeCount": ["D3", "D20"], "hanzi": "終", "composition": ["⿱五日"] },
{ "id": "D87", "isDecomposable": true, "strokeCount": ["D9", "D3"], "hanzi": "出", "composition": ["⿱足五"] },
{ "id": "D88", "isDecomposable": true, "strokeCount": ["D8", "D8"], "hanzi": "二", "composition": ["⿰一一", "＊〢"] },
{ "id": "D89", "isDecomposable": true, "strokeCount": ["D8", "D8", "D8"], "hanzi": "三", "composition": ["⿲一一一", "＊川", "＊〣"] },
{ "id": "D90", "isDecomposable": true, "strokeCount": ["D13", "D73"], "hanzi": "為", "composition": ["⿰少撃"] },
{ "id": "D91", "isDecomposable": true, "strokeCount": ["D9", "D15"], "hanzi": "川", "composition": ["⿱足水"] },
{ "id": "D92", "isDecomposable": true, "strokeCount": ["D15", "D3"], "hanzi": "山", "composition": ["⿱水五"] },
{ "id": "D93", "isDecomposable": true, "strokeCount": ["D15", "D12"], "hanzi": "海", "composition": ["⿱水処"] },
{ "id": "D94", "isDecomposable": true, "strokeCount": ["D10", "D12"], "hanzi": "陸", "composition": ["⿱閉処"] },
{ "id": "D95", "isDecomposable": true, "strokeCount": ["D10", "D3", "D15"], "hanzi": "島", "composition": ["⿳閉五水"] },
{ "id": "D96", "isDecomposable": true, "strokeCount": ["D21", "D55"], "hanzi": "名", "composition": ["⿱言術"] },
{ "id": "D97", "isDecomposable": true, "strokeCount": ["D16", "D11"], "hanzi": "内", "composition": ["⿴口無"] },
{ "id": "D98", "isDecomposable": true, "strokeCount": ["D4", "D7"], "hanzi": "将", "composition": ["⿱人手"] },
{ "id": "D99", "isDecomposable": true, "strokeCount": ["D14", "D16"], "hanzi": "疲", "composition": ["⿵心口"] },
{ "id": "D100", "isDecomposable": true, "strokeCount": ["D6", "D24"], "hanzi": "官", "composition": ["⿱上等"] },
{ "id": "D101", "isDecomposable": true, "strokeCount": ["D21", "D18"], "hanzi": "意", "composition": ["⿱言物"] },
{ "id": "D102", "isDecomposable": true, "strokeCount": ["D24", "D17"], "hanzi": "友", "composition": ["⿲人糸人", "⿴等糸"] },
{ "id": "D103", "isDecomposable": true, "strokeCount": ["D22", "D22"], "hanzi": "値", "composition": ["⿱四四"] },
{ "id": "D104", "isDecomposable": true, "strokeCount": ["D23", "D16"], "hanzi": "受", "composition": ["⿱筆口"] },
{ "id": "D105", "isDecomposable": true, "strokeCount": ["D27", "D11"], "hanzi": "於", "composition": ["⿰大無"] },
{ "id": "D106", "isDecomposable": true, "strokeCount": ["D16", "D7"], "hanzi": "与", "composition": ["⿱口手"] },
{ "id": "D107", "isDecomposable": true, "strokeCount": ["D4", "D22"], "hanzi": "背", "composition": ["⿰人四", "⿺人四"] },
{ "id": "D108", "isDecomposable": true, "strokeCount": ["D88", "D40", "D10", "D58"], "hanzi": "哩", "composition": ["⿲二闇⿱閉論"] },
{ "id": "D109", "isDecomposable": true, "strokeCount": ["D17", "D33"], "hanzi": "布", "composition": ["⿰糸衣"] },
{ "id": "D110", "isDecomposable": true, "strokeCount": ["D31", "D20", "D28"], "hanzi": "新", "composition": ["⿳下日耒"] },
{ "id": "D111", "isDecomposable": true, "strokeCount": ["D6", "D31"], "hanzi": "縦", "composition": ["⿱上下"] },
{ "id": "D112", "isDecomposable": true, "strokeCount": ["D12", "D31"], "hanzi": "低", "composition": ["⿱層一", "⿱処下"] },
{ "id": "D113", "isDecomposable": true, "strokeCount": ["D14", "D31"], "hanzi": "悪", "composition": ["⿱心下"] },
{ "id": "D114", "isDecomposable": true, "strokeCount": ["D9", "D113"], "hanzi": "壊", "composition": ["⿰足悪"] },
{ "id": "D115", "isDecomposable": true, "strokeCount": ["D6", "D4"], "hanzi": "王", "composition": ["⿱上人", "⿳無五人"] },
{ "id": "D116", "isDecomposable": true, "strokeCount": ["D16", "D115"], "hanzi": "国", "composition": ["⿴口王"] },
{ "id": "D117", "isDecomposable": true, "strokeCount": ["D3", "D8"], "hanzi": "六", "composition": ["⿻五一", "＊十"] },
{ "id": "D118", "isDecomposable": true, "strokeCount": ["D3", "D88"], "hanzi": "七", "composition": ["⿻五二", "＊廾"] },
{ "id": "D119", "isDecomposable": true, "strokeCount": ["D3", "D89"], "hanzi": "八", "composition": ["⿻五三", "＊卅"] },
{ "id": "D120", "isDecomposable": true, "strokeCount": ["D6", "D12"], "hanzi": "高", "composition": ["⿱上処", "⿱無層"] },
{ "id": "D121", "isDecomposable": true, "strokeCount": ["D17", "D17"], "hanzi": "綿", "composition": ["⿰糸糸"] },
{ "id": "D122", "isDecomposable": true, "strokeCount": ["D26", "D15"], "hanzi": "油", "composition": ["⿰火水"] },
{ "id": "D123", "isDecomposable": true, "strokeCount": ["D34", "D11", "D11"], "hanzi": "星", "composition": ["⿵天⿱無無"] },
{ "id": "D124", "isDecomposable": true, "strokeCount": ["D123", "D32"], "hanzi": "季", "composition": ["⿺星輪"] },
{ "id": "D125", "isDecomposable": true, "strokeCount": ["D3", "D28"], "hanzi": "入", "composition": ["⿱五耒"] },
{ "id": "D126", "isDecomposable": true, "strokeCount": ["D14", "D125"], "hanzi": "識", "composition": ["⿰心入"] },
{ "id": "D127", "isDecomposable": true, "strokeCount": ["D23", "D125"], "hanzi": "学", "composition": ["⿰筆入"] },
{ "id": "D128", "isDecomposable": true, "strokeCount": ["D28", "D28"], "hanzi": "来", "composition": ["⿱耒耒"] },
{ "id": "D129", "isDecomposable": true, "strokeCount": ["D17", "D17"], "hanzi": "棉", "composition": ["⿱糸糸"] },
{ "id": "D130", "isDecomposable": true, "strokeCount": ["D26", "D20"], "hanzi": "夏", "composition": ["⿱火日"] },
{ "id": "D131", "isDecomposable": true, "strokeCount": ["D7", "D8"], "hanzi": "定", "composition": ["⿰手一"] },
{ "id": "D132", "isDecomposable": true, "strokeCount": ["D13", "D22"], "hanzi": "傷", "composition": ["⿱少四"] },
{ "id": "D133", "isDecomposable": true, "strokeCount": ["D3", "D27"], "hanzi": "棚", "composition": ["⿱五大", "＊王"] },
{ "id": "D134", "isDecomposable": true, "strokeCount": ["D14", "D15"], "hanzi": "血", "composition": ["⿰心水"] },
{ "id": "D135", "isDecomposable": true, "strokeCount": ["D9", "D12"], "hanzi": "道", "composition": ["⿰足処"] },
{ "id": "D136", "isDecomposable": true, "strokeCount": ["D3", "D15"], "hanzi": "吁", "composition": ["⿱五水"] },
{ "id": "D137", "isDecomposable": true, "strokeCount": ["D3", "D4"], "hanzi": "救", "composition": ["⿱五人", "＊天"] },
{ "id": "D138", "isDecomposable": true, "strokeCount": ["D98", "D7"], "hanzi": "従", "composition": ["⿰将人"] },
{ "id": "D139", "isDecomposable": true, "strokeCount": ["D115", "D7"], "hanzi": "从", "composition": ["⿰王人"] },
{ "id": "D140", "isDecomposable": true, "strokeCount": ["D14", "D26"], "hanzi": "奮", "composition": ["⿱心火"] },
{ "id": "D141", "isDecomposable": true, "strokeCount": ["D140", "D15"], "hanzi": "酒", "composition": ["⿰奮水"] },
{ "id": "D142", "isDecomposable": true, "strokeCount": ["D35", "D26"], "hanzi": "煙", "composition": ["⿶包火"] },
{ "id": "D143", "isDecomposable": true, "strokeCount": ["D3", "D35"], "hanzi": "味", "composition": ["⿱五包"] },
{ "id": "D144", "isDecomposable": true, "strokeCount": ["D143", "D6"], "hanzi": "甘", "composition": ["⿱上味"] },
{ "id": "D145", "isDecomposable": true, "strokeCount": ["D35", "D103"], "hanzi": "混", "composition": ["⿶包値"] },
{ "id": "D146", "isDecomposable": true, "strokeCount": ["D27", "D36"], "hanzi": "御", "composition": ["⿰大力"] },
{ "id": "D147", "isDecomposable": true, "strokeCount": ["D4", "D36"], "hanzi": "労", "composition": ["⿰人力"] },
{ "id": "D148", "isDecomposable": true, "strokeCount": ["D36", "D7"], "hanzi": "能", "composition": ["⿺力手"] },
{ "id": "D149", "isDecomposable": true, "strokeCount": ["D107", "D12"], "hanzi": "後", "composition": ["⿱背処"] },
{ "id": "D150", "isDecomposable": true, "strokeCount": ["D85", "D18"], "hanzi": "素", "composition": ["⿱始物"] },
{ "id": "D151", "isDecomposable": true, "strokeCount": ["D107", "D9"], "hanzi": "后", "composition": ["⿱背足"] },
{ "id": "D152", "isDecomposable": true, "strokeCount": ["D23", "D37"], "hanzi": "文", "composition": ["⿰筆連"] },
{ "id": "D153", "isDecomposable": true, "strokeCount": ["D33", "D37"], "hanzi": "聯", "composition": ["⿰衣連"] },
{ "id": "D154", "isDecomposable": true, "strokeCount": ["D37", "D32"], "hanzi": "鎖", "composition": ["⿹連輪"] },
{ "id": "D155", "isDecomposable": true, "strokeCount": ["D37", "D4"], "hanzi": "祖", "composition": ["⿻連人"] },
{ "id": "D156", "isDecomposable": true, "strokeCount": ["D4", "D4"], "hanzi": "多", "composition": ["⿱人人"] },
{ "id": "D157", "isDecomposable": true, "strokeCount": ["D18", "D18"], "hanzi": "極", "composition": ["⿱物物"] },
{ "id": "D158", "isDecomposable": true, "strokeCount": ["D9", "D156"], "hanzi": "増", "composition": ["⿰足多"] },
{ "id": "D159", "isDecomposable": true, "strokeCount": ["D19", "D38"], "hanzi": "笛", "composition": ["⿰声筒"] },
{ "id": "D160", "isDecomposable": true, "strokeCount": ["D38", "D19"], "hanzi": "笙", "composition": ["⿰筒声"] },
{ "id": "D161", "isDecomposable": true, "strokeCount": ["D39", "D176"], "hanzi": "正", "composition": ["⿰直如"] },
{ "id": "D162", "isDecomposable": true, "strokeCount": ["D27", "D39"], "hanzi": "長", "composition": ["⿰大直"] },
{ "id": "D163", "isDecomposable": true, "strokeCount": ["D39", "D90"], "hanzi": "謝", "composition": ["⿰直為"] },
{ "id": "D164", "isDecomposable": true, "strokeCount": ["D19", "D19"], "hanzi": "歌", "composition": ["⿰声声"] },
{ "id": "D165", "isDecomposable": true, "strokeCount": ["D40", "D74"], "hanzi": "寐", "composition": ["⿰闇行"] },
{ "id": "D166", "isDecomposable": true, "strokeCount": ["D20", "D3", "D20"], "hanzi": "恒", "composition": ["⿳日五日"] },
{ "id": "D167", "isDecomposable": true, "strokeCount": ["D4", "D3"], "hanzi": "立", "composition": ["⿱人五"] },
{ "id": "D168", "isDecomposable": true, "strokeCount": ["D23", "D61"], "hanzi": "享", "composition": ["⿱筆果"] },
{ "id": "D169", "isDecomposable": true, "strokeCount": ["D25", "D25"], "hanzi": "隊", "composition": ["⿱兵兵"] },
{ "id": "D170", "isDecomposable": true, "strokeCount": ["D25", "D169"], "hanzi": "軍", "composition": ["⿰兵⿱兵兵"] },
{ "id": "D171", "isDecomposable": true, "strokeCount": ["D3", "D9"], "hanzi": "止", "composition": ["⿱五足"] },
{ "id": "D172", "isDecomposable": true, "strokeCount": ["D10", "D20"], "hanzi": "冬", "composition": ["⿱閉日"] },
{ "id": "D175", "isDecomposable": false, "strokeCount": 3, "hanzi": "石", "composition": ["⿱五己"] },
{ "id": "D176", "isDecomposable": false, "strokeCount": 3, "hanzi": "如", "composition": ["⿸無＊力"] },
{ "id": "D177", "isDecomposable": true, "strokeCount": ["D175", "D7"], "hanzi": "使", "composition": ["⿱石手"] },
{ "id": "D178", "isDecomposable": true, "strokeCount": ["D21", "D175"], "hanzi": "真", "composition": ["⿳言石"] },
{ "id": "D179", "isDecomposable": true, "strokeCount": ["D175", "D176"], "hanzi": "硬", "composition": ["⿰石如"] },
{ "id": "D180", "isDecomposable": true, "strokeCount": ["D129", "D176"], "hanzi": "軟", "composition": ["⿰棉如"] },
{ "id": "D181", "isDecomposable": true, "strokeCount": ["D17", "D176"], "hanzi": "柔", "composition": ["⿰糸如"] },
{ "id": "D183", "isDecomposable": false, "strokeCount": 5, "hanzi": "花", "composition": ["⿱四＊小"] },
{ "id": "D184", "isDecomposable": true, "strokeCount": ["D183", "D15"], "hanzi": "蜜", "composition": ["⿰花水"] },
{ "id": "D185", "isDecomposable": true, "strokeCount": ["D183", "D20"], "hanzi": "春", "composition": ["⿰花日"] },
{ "id": "D186", "isDecomposable": true, "strokeCount": ["D34", "D183"], "hanzi": "雪", "composition": ["⿵天花"] },
{ "id": "D188", "isDecomposable": false, "strokeCount": 3, "hanzi": "机", "composition": ["⿱五＊儿", "＊兀"] },
{ "id": "D189", "isDecomposable": true, "strokeCount": ["D4", "D188"], "hanzi": "席", "composition": ["⿱人机"] },
{ "id": "D190", "isDecomposable": true, "strokeCount": ["D19", "D188"], "hanzi": "箏", "composition": ["⿰声机"] },
{ "id": "D191", "isDecomposable": true, "strokeCount": ["D11", "D188"], "hanzi": "座", "composition": ["⿱無机"] },
{ "id": "D193", "isDecomposable": false, "strokeCount": 2, "hanzi": "再", "composition": ["＊ソ"] },
{ "id": "D194", "isDecomposable": true, "strokeCount": ["D193", "D12"], "hanzi": "在", "composition": ["⿱再処"] },
{ "id": "D195", "isDecomposable": true, "strokeCount": ["D16", "D193", "D3"], "hanzi": "累", "composition": ["⿳口再五"] },
{ "id": "D196", "isDecomposable": true, "strokeCount": ["D193", "D18"], "hanzi": "件", "composition": ["⿱再物"] },
{ "id": "D198", "isDecomposable": false, "strokeCount": 2, "hanzi": "開", "composition": ["＊八", "＊ハ"] },
{ "id": "D199", "isDecomposable": true, "strokeCount": ["D198", "D73"], "hanzi": "勿", "composition": ["⿱開撃"] },
{ "id": "D200", "isDecomposable": true, "strokeCount": ["D9", "D198"], "hanzi": "船", "composition": ["⿱足開"] },
{ "id": "D201", "isDecomposable": true, "strokeCount": ["D6", "D198"], "hanzi": "散", "composition": ["⿱上開"] },
{ "id": "D203", "isDecomposable": false, "strokeCount": 2, "hanzi": "風", "composition": ["＊刀"] },
{ "id": "D204", "isDecomposable": true, "strokeCount": ["D203", "D3"], "hanzi": "月", "composition": ["⿱風五"] },
{ "id": "D205", "isDecomposable": true, "strokeCount": ["D203", "D12"], "hanzi": "弓", "composition": ["⿻風処"] },
{ "id": "D206", "isDecomposable": true, "strokeCount": ["D205", "D36"], "hanzi": "抗", "composition": ["⿰弓力"] },
{ "id": "D208", "isDecomposable": false, "strokeCount": 3.6, "hanzi": "樽", "composition": ["＊ㅂ"] },
{ "id": "D209", "isDecomposable": true, "strokeCount": ["D19", "D208"], "hanzi": "鼓", "composition": ["⿸声樽"] },
{ "id": "D210", "isDecomposable": true, "strokeCount": ["D19", "D208"], "hanzi": "皷", "composition": ["⿰樽声"] },
{ "id": "D211", "isDecomposable": true, "strokeCount": ["D3", "D208"], "hanzi": "深", "composition": ["⿱樽五", "＊브"] },
{ "id": "D213", "isDecomposable": false, "strokeCount": 3, "hanzi": "圧", "composition": ["⿱＊冖五"] },
{ "id": "D214", "isDecomposable": true, "strokeCount": ["D23", "D213"], "hanzi": "絵", "composition": ["⿱筆圧"] },
{ "id": "D216", "isDecomposable": false, "strokeCount": 7, "hanzi": "同", "composition": ["⿻⿱口口一", "＊串"] },
{ "id": "D217", "isDecomposable": true, "strokeCount": ["D216", "D4"], "hanzi": "輩", "composition": ["⿱同人"] },
{ "id": "D218", "isDecomposable": true, "strokeCount": ["D216", "D24"], "hanzi": "類", "composition": ["⿰同等"] },
{ "id": "D219", "isDecomposable": true, "strokeCount": ["D216", "D156"], "hanzi": "属", "composition": ["⿰同多"] },
{ "id": "D221", "isDecomposable": false, "strokeCount": 3, "hanzi": "軸", "composition": ["⿻処一", "＊キ"] },
{ "id": "D222", "isDecomposable": true, "strokeCount": ["D123", "D221"], "hanzi": "北", "composition": ["⿺星軸"] },
{ "id": "D223", "isDecomposable": true, "strokeCount": ["D222", "D23"], "hanzi": "翰", "composition": ["⿰軸筆"] },
{ "id": "D226", "isDecomposable": false, "strokeCount": 2, "hanzi": "??", "composition": ["＊冖"] },
{ "id": "D227", "isDecomposable": true, "strokeCount": ["D226", "D32"], "hanzi": "車", "composition": ["⿱＊冖輪"] },
{ "id": "D228", "isDecomposable": true, "strokeCount": ["D226", "D27", "D221"], "hanzi": "冠", "composition": ["⿱＊冖⿰大軸"] },
{ "id": "D229", "isDecomposable": true, "strokeCount": ["D226", "D213"], "hanzi": "積", "composition": ["⿱＊冖圧"] },
{ "id": "D230", "isDecomposable": true, "strokeCount": ["D4", "D229"], "hanzi": "族", "composition": ["⿰人積"] },
{ "id": "D232", "isDecomposable": false, "strokeCount": 2, "hanzi": "??", "composition": ["⿹神少"] },
{ "id": "D233", "isDecomposable": true, "strokeCount": ["D232", "D3"], "hanzi": "亦", "composition": ["⿱％右風", "⿺⿹神少五"] },
{ "id": "D234", "isDecomposable": true, "strokeCount": ["D233", "D11"], "hanzi": "乎", "composition": ["⿻亦無"] },
{ "id": "D235", "isDecomposable": true, "strokeCount": ["D232", "D3"], "hanzi": "地", "composition": ["⿱⿹神少五"] },
{ "id": "D238", "isDecomposable": false, "strokeCount": 4, "hanzi": "平", "composition": ["⿴口一"] },
{ "id": "D239", "isDecomposable": true, "strokeCount": ["D238", "D4"], "hanzi": "守", "composition": ["⿰平人"] },
{ "id": "D240", "isDecomposable": true, "strokeCount": ["D238", "D6"], "hanzi": "美", "composition": ["⿱平上"] },
{ "id": "D242", "isDecomposable": false, "strokeCount": 4, "hanzi": "獣", "composition": ["＊勿"] },
{ "id": "D243", "isDecomposable": true, "strokeCount": ["D12", "D242"], "hanzi": "馬", "composition": ["⿻処獣"] },
{ "id": "D244", "isDecomposable": true, "strokeCount": ["D10", "D242"], "hanzi": "貓", "composition": ["⿱閉獣"] },
{ "id": "D246", "isDecomposable": false, "strokeCount": 4, "hanzi": "男", "composition": ["⿻人少"] },
{ "id": "D247", "isDecomposable": true, "strokeCount": ["D6", "D246"], "hanzi": "父", "composition": ["⿱上男"] },
{ "id": "D248", "isDecomposable": true, "strokeCount": ["D19", "D247"], "hanzi": "㕮", "composition": ["⿰声父"] },
{ "id": "D250", "isDecomposable": false, "strokeCount": 4, "hanzi": "周", "composition": ["⿻処二", "＊井"] },
{ "id": "D251", "isDecomposable": true, "strokeCount": ["D9", "D250"], "hanzi": "近", "composition": ["⿰足周"] },
{ "id": "D252", "isDecomposable": true, "strokeCount": ["D250", "D27"], "hanzi": "広", "composition": ["⿱周大"] },
{ "id": "D254", "isDecomposable": false, "strokeCount": 4, "hanzi": "草", "composition": ["⿱＊ツ五"] },
{ "id": "D255", "isDecomposable": true, "strokeCount": ["D3", "D254"], "hanzi": "種", "composition": ["⿱五草"] },
{ "id": "D256", "isDecomposable": true, "strokeCount": ["D254", "D15"], "hanzi": "茶", "composition": ["⿱草水"] },
{ "id": "D258", "isDecomposable": false, "strokeCount": 3, "hanzi": "小", "composition": ["⿱五六", "＊干"] },
{ "id": "D259", "isDecomposable": true, "strokeCount": ["D258", "D90"], "hanzi": "挽", "composition": ["⿰小為"] },
{ "id": "D260", "isDecomposable": true, "strokeCount": ["D258", "D39"], "hanzi": "短", "composition": ["⿰小直"] },
{ "id": "D262", "isDecomposable": false, "strokeCount": 4, "hanzi": "銭", "composition": ["⿱％六⿹衣無"] },
{ "id": "D263", "isDecomposable": true, "strokeCount": ["D262", "D12"], "hanzi": "店", "composition": ["⿱銭処"] },
{ "id": "D264", "isDecomposable": false, "strokeCount": 4.6, "hanzi": "貧", "composition": ["⿸％少銭"] },
{ "id": "D266", "isDecomposable": false, "strokeCount": 2, "hanzi": "左", "composition": ["⿻＊亅少"] },
{ "id": "D267", "isDecomposable": true, "strokeCount": ["D266", "D10"], "hanzi": "倒", "composition": ["⿰左閉"] },
{ "id": "D269", "isDecomposable": false, "strokeCount": 2, "hanzi": "而", "composition": ["⿻＊亅＊㇀"] },
{ "id": "D270", "isDecomposable": true, "strokeCount": ["D269", "D269"], "hanzi": "即", "composition": ["⿰而而"] },
{ "id": "D272", "isDecomposable": false, "strokeCount": 6, "hanzi": "木", "composition": ["⿻再＊木", "＊米"] },
{ "id": "D273", "isDecomposable": true, "strokeCount": ["D272", "D38"], "hanzi": "竹", "composition": ["⿰木筒"] },
{ "id": "D274", "isDecomposable": true, "strokeCount": ["D38", "D272"], "hanzi": "竺", "composition": ["⿰筒木"] },
{ "id": "D276", "isDecomposable": false, "strokeCount": 3, "hanzi": "色", "composition": ["⿰少九"] },
{ "id": "D277", "isDecomposable": true, "strokeCount": ["D276", "D40"], "hanzi": "黒", "composition": ["⿰色闇"] },
{ "id": "D278", "isDecomposable": true, "strokeCount": ["D276", "D15"], "hanzi": "青", "composition": ["⿰色水"] },
{ "id": "D281", "isDecomposable": false, "strokeCount": 3, "hanzi": "岩", "composition": ["⿱少己"] },
{ "id": "D282", "isDecomposable": true, "strokeCount": ["D11", "D281"], "hanzi": "欽", "composition": ["⿸無岩"] },
{ "id": "D284", "isDecomposable": false, "strokeCount": 5, "hanzi": "西", "composition": ["⿱％一日", "⿻＊冖大", "⿻六口", "＊由"] },
{ "id": "D285", "isDecomposable": true, "strokeCount": ["D3", "D284"], "hanzi": "菓", "composition": ["⿱五西"] },
{ "id": "D287", "isDecomposable": false, "strokeCount": 4.3, "hanzi": "膠", "composition": ["⿱⿻＊了再五"] },
{ "id": "D288", "isDecomposable": true, "strokeCount": ["D26", "D287"], "hanzi": "脂", "composition": ["⿰火膠"] },
{ "id": "D290", "isDecomposable": false, "strokeCount": 5, "hanzi": "骨", "composition": ["⿻天軸"] },
{ "id": "D291", "isDecomposable": true, "strokeCount": ["D10", "D290"], "hanzi": "肉", "composition": ["⿱閉骨"] },
{ "id": "D293", "isDecomposable": false, "strokeCount": 3, "hanzi": "彼", "composition": ["＊己"] },
{ "id": "D294", "isDecomposable": true, "strokeCount": ["D118", "D293"], "hanzi": "龍", "composition": ["⿱七彼"] },
{ "id": "D296", "isDecomposable": false, "strokeCount": 3.6, "hanzi": "錘", "composition": ["⿹力＊㇀"] },
{ "id": "D297", "isDecomposable": true, "strokeCount": ["D27", "D296"], "hanzi": "禦", "composition": ["⿰大錘"] },
{ "id": "D299", "isDecomposable": false, "strokeCount": 5, "hanzi": "目", "composition": ["⿴口二", "＊罒"] },
{ "id": "D300", "isDecomposable": true, "strokeCount": ["D299", "D6"], "hanzi": "麗", "composition": ["⿱目上"] },
{ "id": "D302", "isDecomposable": false, "strokeCount": 2, "hanzi": "箱", "composition": ["＊匸"] },
{ "id": "D303", "isDecomposable": true, "strokeCount": ["D302", "D32"], "hanzi": "機", "composition": ["⿷箱輪"] },
{ "id": "D305", "isDecomposable": false, "strokeCount": 2, "hanzi": "門", "composition": ["＊冂"] },
{ "id": "D306", "isDecomposable": true, "strokeCount": ["D305", "D32"], "hanzi": "械", "composition": ["⿻門輪"] },
{ "id": "D308", "isDecomposable": false, "strokeCount": 1, "hanzi": "十", "composition": ["＊乙"] },
{ "id": "D309", "isDecomposable": true, "strokeCount": ["D308", "D11"], "hanzi": "唯", "composition": ["⿻十無"] },
{ "id": "D311", "isDecomposable": false, "strokeCount": 2, "hanzi": "鳥", "composition": ["＊𠤎"] },
{ "id": "D312", "isDecomposable": true, "strokeCount": ["D10", "D311"], "hanzi": "倉", "composition": ["⿱閉鳥"] },
{ "id": "D314", "isDecomposable": false, "strokeCount": 2, "hanzi": "右", "composition": ["⿰一無", "＊ト", "＊卜"] },
{ "id": "D315", "isDecomposable": true, "strokeCount": ["D266", "D314"], "hanzi": "横", "composition": ["⿰左右"] },
{ "id": "D317", "isDecomposable": false, "strokeCount": 4, "hanzi": "虎", "composition": ["⿱％五獣"] },
{ "id": "D318", "isDecomposable": true, "strokeCount": ["D10", "D317"], "hanzi": "猫", "composition": ["⿱閉虎"] },
{ "id": "D320", "isDecomposable": false, "strokeCount": 4, "hanzi": "女", "composition": ["⿻少腹"] },
{ "id": "D321", "isDecomposable": true, "strokeCount": ["D6", "D320"], "hanzi": "母", "composition": ["⿱上女"] },
{ "id": "D323", "isDecomposable": false, "strokeCount": 3, "hanzi": "腹", "composition": ["⿻五四", "＊丈"] },
{ "id": "D324", "isDecomposable": true, "strokeCount": ["D323", "D12"], "hanzi": "前", "composition": ["⿱腹処"] },
{ "id": "D326", "isDecomposable": false, "strokeCount": 5, "hanzi": "巫", "composition": ["⿻口之"] },
{ "id": "D327", "isDecomposable": true, "strokeCount": ["D326", "D26"], "hanzi": "祭", "composition": ["⿰巫火"] },
{ "id": "D329", "isDecomposable": false, "strokeCount": 4, "hanzi": "別", "composition": ["⿲＊㇀＊儿無"] },
{ "id": "D330", "isDecomposable": true, "strokeCount": ["D329", "D18"], "hanzi": "裁", "composition": ["⿱別物"] },
{ "id": "D332", "isDecomposable": false, "strokeCount": 5, "hanzi": "米", "composition": ["＊氺"] },
{ "id": "D333", "isDecomposable": false, "strokeCount": 3, "hanzi": "刀", "composition": ["⿰一六", "⿻上一", "＊丩"] },
{ "id": "D334", "isDecomposable": true, "strokeCount": ["D332", "D333"], "hanzi": "秋", "composition": ["⿰米刀"] },
{ "id": "D336", "isDecomposable": false, "strokeCount": 1, "hanzi": "神", "composition": ["＊㇉"] },
{ "id": "D337", "isDecomposable": false, "strokeCount": 3, "hanzi": "或", "composition": ["＊々"] },
{ "id": "D338", "isDecomposable": false, "strokeCount": 2, "hanzi": "位", "composition": ["＊乃"] },
{ "id": "D339", "isDecomposable": false, "strokeCount": 5, "hanzi": "字", "composition": ["⿱九⿻＊フ⿺＊乚無"] },
{ "id": "D340", "isDecomposable": false, "strokeCount": 3, "hanzi": "谷", "composition": ["＊刄"] },
{ "id": "D341", "isDecomposable": false, "strokeCount": 3, "hanzi": "魚", "composition": ["⿻＊レ⿺＊㇏少"] },
{ "id": "D342", "isDecomposable": false, "strokeCount": 5, "hanzi": "虫", "composition": ["⿻包筆"] },
{ "id": "D343", "isDecomposable": false, "strokeCount": 5, "hanzi": "皇", "composition": ["⿻＊冖軸", "⿻口六", "⿻＊中五"] },
{ "id": "D344", "isDecomposable": false, "strokeCount": 3, "hanzi": "貝", "composition": ["＊彡"] },
{ "id": "D345", "isDecomposable": false, "strokeCount": 2, "hanzi": "函", "composition": ["＊コ"] },
{ "id": "D346", "isDecomposable": false, "strokeCount": 3, "hanzi": "中", "composition": ["⿱五上", "＊工", "＊エ"] },
{ "id": "D347", "isDecomposable": true, "strokeCount": 6, "hanzi": "外", "composition": ["⿰＊ㅌ＊ヨ", "⿰＊ㅌ＊크"] },
{ "id": "D348", "isDecomposable": false, "strokeCount": 5, "hanzi": "東", "composition": ["⿱％日一", "⿵＊冖軸", "⿻口六", "＊甲"] },
{ "id": "D349", "isDecomposable": false, "strokeCount": 7, "hanzi": "南", "composition": ["⿱％東大", "⿻東処", "⿻言大", "＊里"] },
{ "id": "D350", "isDecomposable": false, "strokeCount": 2, "hanzi": "九", "composition": ["⿱％五四", "＊ヌ", "＊又"] },
{ "id": "D351", "isDecomposable": false, "strokeCount": 3, "hanzi": "加", "composition": ["⿻五＊儿"] },
{ "id": "D352", "isDecomposable": false, "strokeCount": 5, "hanzi": "金", "composition": ["⿻再石"] },
{ "id": "D353", "isDecomposable": true, "strokeCount": 5, "hanzi": "夘", "composition": ["⿰＊ㅌ右"] },
{ "id": "D354", "isDecomposable": false, "strokeCount": 1, "hanzi": "反", "composition": ["＊レ"] },
{ "id": "D355", "isDecomposable": false, "strokeCount": 4, "hanzi": "耳", "composition": ["⿻少＊ヨ"] },
{ "id": "D356", "isDecomposable": false, "strokeCount": 4, "hanzi": "助", "composition": ["＊开"] },
{ "id": "D357", "isDecomposable": false, "strokeCount": 8, "hanzi": "豆", "composition": ["⿳五⿻⿻再六再五", "⿳五⿻端再五"] },
{ "id": "D358", "isDecomposable": false, "strokeCount": 4, "hanzi": "嗅", "composition": ["⿻筆一"] },
{ "id": "D359", "isDecomposable": false, "strokeCount": 2, "hanzi": "傾", "composition": ["＊厂"] },
{ "id": "D360", "isDecomposable": false, "strokeCount": 6, "hanzi": "震", "composition": ["⿲無＊中少"] },
{ "id": "D361", "isDecomposable": false, "strokeCount": 4, "hanzi": "端", "composition": ["⿻再六"] },
{ "id": "D362", "isDecomposable": false, "strokeCount": 2, "hanzi": "歪", "composition": ["⿱＊フ十"] },
{ "id": "D363", "isDecomposable": false, "strokeCount": 4, "hanzi": "片", "composition": ["⿱五＊山"] },
{ "id": "D364", "isDecomposable": false, "strokeCount": 1, "hanzi": "針", "composition": ["＊亅"] }];
