const non_linzi_id_list = allElements()(["＊ㄉ", "＊フ"]);
const composition2 = {
    "五": { "index": 3, "isDecomposable": false, "strokeCount": 1, "hanzi": "五", "composition": ["＊一"] },
    "人": { "index": 4, "isDecomposable": false, "strokeCount": 3, "hanzi": "人", "composition": ["＊大"] },
    "之": { "index": 5, "isDecomposable": false, "strokeCount": 2, "hanzi": "之", "composition": ["＊人"] },
    "上": { "index": 6, "isDecomposable": false, "strokeCount": 2, "hanzi": "上", "composition": ["⿱一五", "＊丄"] },
    "手": { "index": 7, "isDecomposable": false, "strokeCount": 3, "hanzi": "手", "composition": ["＊屮"] },
    "一": { "index": 8, "isDecomposable": false, "strokeCount": 1, "hanzi": "一", "composition": ["＊丨", "＊〡"] },
    "足": { "index": 9, "isDecomposable": false, "strokeCount": 3.6, "hanzi": "足", "composition": ["＊廿"] },
    "閉": { "index": 10, "isDecomposable": false, "strokeCount": 2, "hanzi": "閉", "composition": ["＊𠆢"] },
    "無": { "index": 11, "isDecomposable": false, "strokeCount": 1, "hanzi": "無", "composition": ["＊丶"] },
    "処": { "index": 12, "isDecomposable": true, "strokeCount": ["五", "五"], "hanzi": "処", "composition": ["⿱五五", "＊二", "＊ニ"] },
    "少": { "index": 13, "isDecomposable": false, "strokeCount": 1, "hanzi": "少", "composition": ["＊丿"] },
    "心": { "index": 14, "isDecomposable": false, "strokeCount": 5, "hanzi": "心", "composition": ["⿻再人"] },
    "水": { "index": 15, "isDecomposable": true, "strokeCount": ["之", "之"], "hanzi": "水", "composition": ["⿰之之", "＊ㅆ", "＊从"] },
    "口": { "index": 16, "isDecomposable": false, "strokeCount": 3, "hanzi": "口", "composition": ["＊口", "＊ロ"] },
    "糸": { "index": 17, "isDecomposable": false, "strokeCount": 4, "hanzi": "糸", "composition": ["⿳五再五", "＊ㅍ"] },
    "物": { "index": 18, "isDecomposable": false, "strokeCount": 2, "hanzi": "物", "composition": ["＊マ"] },
    "声": { "index": 19, "isDecomposable": false, "strokeCount": 3, "hanzi": "声", "composition": ["＊万"] },
    "日": { "index": 20, "isDecomposable": false, "strokeCount": 5, "hanzi": "日", "composition": ["⿴口六", "＊田"] },
    "言": { "index": 21, "isDecomposable": false, "strokeCount": 4, "hanzi": "言", "composition": ["⿴口五", "＊日", "＊曰"] },
    "四": { "index": 22, "isDecomposable": false, "strokeCount": 2, "hanzi": "四", "composition": ["＊メ", "＊〤"] },
    "筆": { "index": 23, "isDecomposable": false, "strokeCount": 3, "hanzi": "筆", "composition": ["＊巾"] },
    "等": { "index": 24, "isDecomposable": true, "strokeCount": ["人", "人"], "hanzi": "等", "composition": ["⿰人人"] },
    "兵": { "index": 25, "isDecomposable": true, "strokeCount": ["少", "人"], "hanzi": "兵", "composition": ["⿰少人"] },
    "火": { "index": 26, "isDecomposable": false, "strokeCount": 3, "hanzi": "火", "composition": ["⿶四無", "＊义"] },
    "大": { "index": 27, "isDecomposable": false, "strokeCount": 3, "hanzi": "大", "composition": ["⿱六五", "＊土", "＊士"] },
    "耒": { "index": 28, "isDecomposable": false, "strokeCount": 3, "hanzi": "耒", "composition": ["⿻門五"] },
    "光": { "index": 29, "isDecomposable": false, "strokeCount": 3, "hanzi": "光", "composition": ["⿻再＊亅"] },
    "己": { "index": 30, "isDecomposable": false, "strokeCount": 2, "hanzi": "己", "composition": ["＊ム", "＊厶"] },
    "下": { "index": 31, "isDecomposable": false, "strokeCount": 2, "hanzi": "下", "composition": ["⿱五一", "＊丅"] },
    "輪": { "index": 32, "isDecomposable": false, "strokeCount": 5, "hanzi": "輪", "composition": ["＊毌"] },
    "衣": { "index": 33, "isDecomposable": false, "strokeCount": 2, "hanzi": "衣", "composition": ["＊卩"] },
    "天": { "index": 34, "isDecomposable": false, "strokeCount": 2, "hanzi": "天", "composition": ["＊𠘨"] },
    "包": { "index": 35, "isDecomposable": false, "strokeCount": 2, "hanzi": "包", "composition": ["＊凵"] },
    "力": { "index": 36, "isDecomposable": false, "strokeCount": 3, "hanzi": "力", "composition": ["⿱五⿰少十"] },
    "連": { "index": 37, "isDecomposable": false, "strokeCount": ["＊フ", "神"], "hanzi": "連", "composition": ["⿹＊フ神"] },
    "筒": { "index": 38, "isDecomposable": false, "strokeCount": 4, "hanzi": "筒", "composition": ["＊ㅒ"] },
    "直": { "index": 39, "isDecomposable": false, "strokeCount": 4, "hanzi": "直", "composition": ["＊丰"] },
    "闇": { "index": 40, "isDecomposable": true, "strokeCount": ["閉", "光"], "hanzi": "闇", "composition": ["⿱閉光"] },
    "我": { "index": 46, "isDecomposable": true, "strokeCount": ["人", "己"], "hanzi": "我", "composition": ["⿰人己", "⿺人己"] },
    "汝": { "index": 47, "isDecomposable": true, "strokeCount": ["人", "物"], "hanzi": "汝", "composition": ["⿰人物", "⿺人物"] },
    "此": { "index": 48, "isDecomposable": true, "strokeCount": ["己", "口"], "hanzi": "此", "composition": ["⿱己口"] },
    "其": { "index": 49, "isDecomposable": true, "strokeCount": ["物", "口"], "hanzi": "其", "composition": ["⿱物口"] },
    "何": { "index": 50, "isDecomposable": true, "strokeCount": ["心", "無"], "hanzi": "何", "composition": ["⿵心無"] },
    "全": { "index": 51, "isDecomposable": true, "strokeCount": ["口", "物"], "hanzi": "全", "composition": ["⿴口物"] },
    "互": { "index": 52, "isDecomposable": true, "strokeCount": ["物", "己"], "hanzi": "互", "composition": ["⿱物己"] },
    "時": { "index": 53, "isDecomposable": true, "strokeCount": ["日", "足"], "hanzi": "時", "composition": ["⿱日足"] },
    "故": { "index": 54, "isDecomposable": true, "strokeCount": ["言", "上"], "hanzi": "故", "composition": ["⿱言上"] },
    "術": { "index": 55, "isDecomposable": true, "strokeCount": ["手", "手"], "hanzi": "術", "composition": ["⿰手手", "＊艸"] },
    "書": { "index": 56, "isDecomposable": true, "strokeCount": ["筆", "処"], "hanzi": "書", "composition": ["⿱筆処"] },
    "墨": { "index": 57, "isDecomposable": true, "strokeCount": ["筆", "水"], "hanzi": "墨", "composition": ["⿰筆水"] },
    "論": { "index": 58, "isDecomposable": true, "strokeCount": ["言", "言"], "hanzi": "論", "composition": ["⿱言言"] },
    "紙": { "index": 59, "isDecomposable": true, "strokeCount": ["筆", "衣"], "hanzi": "紙", "composition": ["⿰筆衣"] },
    "頭": { "index": 60, "isDecomposable": true, "strokeCount": ["四", "人"], "hanzi": "頭", "composition": ["⿱四人"] },
    "果": { "index": 61, "isDecomposable": true, "strokeCount": ["人", "口"], "hanzi": "果", "composition": ["⿱人口"] },
    "満": { "index": 62, "isDecomposable": true, "strokeCount": ["閉", "五"], "hanzi": "満", "composition": ["⿱閉五"] },
    "清": { "index": 63, "isDecomposable": true, "strokeCount": ["上", "衣"], "hanzi": "清", "composition": ["⿱上衣"] },
    "牌": { "index": 64, "isDecomposable": true, "strokeCount": ["己", "等"], "hanzi": "牌", "composition": ["⿱己等"] },
    "豊": { "index": 65, "isDecomposable": true, "strokeCount": ["物", "等"], "hanzi": "豊", "composition": ["⿱物等"] },
    "家": { "index": 66, "isDecomposable": true, "strokeCount": ["閉", "上"], "hanzi": "家", "composition": ["⿱閉上", "＊소"] },
    "善": { "index": 67, "isDecomposable": true, "strokeCount": ["上", "心"], "hanzi": "善", "composition": ["⿱上心"] },
    "認": { "index": 68, "isDecomposable": true, "strokeCount": ["言", "善"], "hanzi": "認", "composition": ["⿰言善"] },
    "寝": { "index": 69, "isDecomposable": true, "strokeCount": ["足", "闇"], "hanzi": "寝", "composition": ["⿰足闇"] },
    "覆": { "index": 70, "isDecomposable": true, "strokeCount": ["閉", "己"], "hanzi": "覆", "composition": ["⿱閉己"] },
    "琴": { "index": 71, "isDecomposable": true, "strokeCount": ["糸", "声"], "hanzi": "琴", "composition": ["⿰糸声"] },
    "古": { "index": 72, "isDecomposable": true, "strokeCount": ["上", "時"], "hanzi": "古", "composition": ["⿱上時"] },
    "撃": { "index": 73, "isDecomposable": true, "strokeCount": ["五", "手"], "hanzi": "撃", "composition": ["⿱五手"] },
    "行": { "index": 74, "isDecomposable": true, "strokeCount": ["足", "足"], "hanzi": "行", "composition": ["⿱足足"] },
    "囲": { "index": 75, "isDecomposable": true, "strokeCount": ["口", "人"], "hanzi": "囲", "composition": ["⿴口人", "＊因"] },
    "党": { "index": 76, "isDecomposable": true, "strokeCount": ["言", "等"], "hanzi": "党", "composition": ["⿱言等"] },
    "笑": { "index": 77, "isDecomposable": true, "strokeCount": ["足", "善"], "hanzi": "笑", "composition": ["⿰足善"] },
    "戦": { "index": 78, "isDecomposable": true, "strokeCount": ["兵", "兵"], "hanzi": "戦", "composition": ["⿰兵兵"] },
    "静": { "index": 79, "isDecomposable": true, "strokeCount": ["声", "無"], "hanzi": "静", "composition": ["⿻声無", "⿱五⿰四＊𠃌"] },
    "層": { "index": 80, "isDecomposable": true, "strokeCount": ["五", "処"], "hanzi": "層", "composition": ["⿱五処"] },
    "噫": { "index": 81, "isDecomposable": true, "strokeCount": ["心", "声"], "hanzi": "噫", "composition": ["⿰心声"] },
    "律": { "index": 82, "isDecomposable": true, "strokeCount": ["筆", "糸"], "hanzi": "律", "composition": ["⿰筆糸"] },
    "集": { "index": 83, "isDecomposable": true, "strokeCount": ["等", "五"], "hanzi": "集", "composition": ["⿱等五"] },
    "輝": { "index": 84, "isDecomposable": true, "strokeCount": ["日", "光"], "hanzi": "輝", "composition": ["⿱日光"] },
    "始": { "index": 85, "isDecomposable": true, "strokeCount": ["日", "五"], "hanzi": "始", "composition": ["⿱日五"] },
    "終": { "index": 86, "isDecomposable": true, "strokeCount": ["五", "日"], "hanzi": "終", "composition": ["⿱五日"] },
    "生": { "index": 87, "isDecomposable": true, "strokeCount": ["足", "五"], "hanzi": "生", "composition": ["⿱足五"] },
    "二": { "index": 88, "isDecomposable": true, "strokeCount": ["一", "一"], "hanzi": "二", "composition": ["⿰一一", "＊〢"] },
    "三": { "index": 89, "isDecomposable": true, "strokeCount": ["一", "一", "一"], "hanzi": "三", "composition": ["⿲一一一", "＊川", "＊〣"] },
    "為": { "index": 90, "isDecomposable": true, "strokeCount": ["少", "撃"], "hanzi": "為", "composition": ["⿰少撃"] },
    "川": { "index": 91, "isDecomposable": true, "strokeCount": ["足", "水"], "hanzi": "川", "composition": ["⿱足水"] },
    "山": { "index": 92, "isDecomposable": true, "strokeCount": ["水", "五"], "hanzi": "山", "composition": ["⿱水五"] },
    "海": { "index": 93, "isDecomposable": true, "strokeCount": ["水", "処"], "hanzi": "海", "composition": ["⿱水処"] },
    "陸": { "index": 94, "isDecomposable": true, "strokeCount": ["閉", "処"], "hanzi": "陸", "composition": ["⿱閉処"] },
    "島": { "index": 95, "isDecomposable": true, "strokeCount": ["閉", "五", "水"], "hanzi": "島", "composition": ["⿳閉五水"] },
    "名": { "index": 96, "isDecomposable": true, "strokeCount": ["言", "術"], "hanzi": "名", "composition": ["⿱言術"] },
    "内": { "index": 97, "isDecomposable": true, "strokeCount": ["口", "無"], "hanzi": "内", "composition": ["⿴口無"] },
    "将": { "index": 98, "isDecomposable": true, "strokeCount": ["人", "手"], "hanzi": "将", "composition": ["⿱人手"] },
    "疲": { "index": 99, "isDecomposable": true, "strokeCount": ["心", "口"], "hanzi": "疲", "composition": ["⿵心口"] },
    "官": { "index": 100, "isDecomposable": true, "strokeCount": ["上", "等"], "hanzi": "官", "composition": ["⿱上等"] },
    "意": { "index": 101, "isDecomposable": true, "strokeCount": ["言", "物"], "hanzi": "意", "composition": ["⿱言物"] },
    "友": { "index": 102, "isDecomposable": true, "strokeCount": ["等", "糸"], "hanzi": "友", "composition": ["⿲人糸人", "⿴等糸"] },
    "値": { "index": 103, "isDecomposable": true, "strokeCount": ["四", "四"], "hanzi": "値", "composition": ["⿱四四"] },
    "受": { "index": 104, "isDecomposable": true, "strokeCount": ["筆", "口"], "hanzi": "受", "composition": ["⿱筆口"] },
    "於": { "index": 105, "isDecomposable": true, "strokeCount": ["大", "無"], "hanzi": "於", "composition": ["⿰大無"] },
    "与": { "index": 106, "isDecomposable": true, "strokeCount": ["口", "手"], "hanzi": "与", "composition": ["⿱口手"] },
    "背": { "index": 107, "isDecomposable": true, "strokeCount": ["人", "四"], "hanzi": "背", "composition": ["⿰人四", "⿺人四"] },
    "哩": { "index": 108, "isDecomposable": true, "strokeCount": ["二", "闇", "閉", "論"], "hanzi": "哩", "composition": ["⿲二闇⿱閉論"] },
    "布": { "index": 109, "isDecomposable": true, "strokeCount": ["糸", "衣"], "hanzi": "布", "composition": ["⿰糸衣"] },
    "新": { "index": 110, "isDecomposable": true, "strokeCount": ["下", "日", "耒"], "hanzi": "新", "composition": ["⿳下日耒"] },
    "縦": { "index": 111, "isDecomposable": true, "strokeCount": ["上", "下"], "hanzi": "縦", "composition": ["⿱上下"] },
    "低": { "index": 112, "isDecomposable": true, "strokeCount": ["処", "下"], "hanzi": "低", "composition": ["⿱層一", "⿱処下"] },
    "悪": { "index": 113, "isDecomposable": true, "strokeCount": ["心", "下"], "hanzi": "悪", "composition": ["⿱心下"] },
    "壊": { "index": 114, "isDecomposable": true, "strokeCount": ["足", "悪"], "hanzi": "壊", "composition": ["⿰足悪"] },
    "王": { "index": 115, "isDecomposable": true, "strokeCount": ["上", "人"], "hanzi": "王", "composition": ["⿱上人", "⿳無五人"] },
    "国": { "index": 116, "isDecomposable": true, "strokeCount": ["口", "王"], "hanzi": "国", "composition": ["⿴口王"] },
    "六": { "index": 117, "isDecomposable": true, "strokeCount": ["五", "一"], "hanzi": "六", "composition": ["⿻五一", "＊十"] },
    "七": { "index": 118, "isDecomposable": true, "strokeCount": ["五", "二"], "hanzi": "七", "composition": ["⿻五二", "＊廾"] },
    "八": { "index": 119, "isDecomposable": true, "strokeCount": ["五", "三"], "hanzi": "八", "composition": ["⿻五三", "＊卅"] },
    "高": { "index": 120, "isDecomposable": true, "strokeCount": ["上", "処"], "hanzi": "高", "composition": ["⿱上処", "⿱無層"] },
    "綿": { "index": 121, "isDecomposable": true, "strokeCount": ["糸", "糸"], "hanzi": "綿", "composition": ["⿰糸糸"] },
    "油": { "index": 122, "isDecomposable": true, "strokeCount": ["火", "水"], "hanzi": "油", "composition": ["⿰火水"] },
    "星": { "index": 123, "isDecomposable": true, "strokeCount": ["天", "無", "無"], "hanzi": "星", "composition": ["⿵天⿱無無"] },
    "季": { "index": 124, "isDecomposable": true, "strokeCount": ["星", "輪"], "hanzi": "季", "composition": ["⿺星輪"] },
    "入": { "index": 125, "isDecomposable": true, "strokeCount": ["五", "耒"], "hanzi": "入", "composition": ["⿱五耒"] },
    "識": { "index": 126, "isDecomposable": true, "strokeCount": ["心", "入"], "hanzi": "識", "composition": ["⿰心入"] },
    "学": { "index": 127, "isDecomposable": true, "strokeCount": ["筆", "入"], "hanzi": "学", "composition": ["⿰筆入"] },
    "来": { "index": 128, "isDecomposable": true, "strokeCount": ["耒", "耒"], "hanzi": "来", "composition": ["⿱耒耒"] },
    "棉": { "index": 129, "isDecomposable": true, "strokeCount": ["糸", "糸"], "hanzi": "棉", "composition": ["⿱糸糸"] },
    "夏": { "index": 130, "isDecomposable": true, "strokeCount": ["火", "日"], "hanzi": "夏", "composition": ["⿱火日"] },
    "定": { "index": 131, "isDecomposable": true, "strokeCount": ["手", "一"], "hanzi": "定", "composition": ["⿰手一"] },
    "傷": { "index": 132, "isDecomposable": true, "strokeCount": ["少", "四"], "hanzi": "傷", "composition": ["⿱少四"] },
    "棚": { "index": 133, "isDecomposable": true, "strokeCount": ["五", "大"], "hanzi": "棚", "composition": ["⿱五大", "＊王"] },
    "血": { "index": 134, "isDecomposable": true, "strokeCount": ["心", "水"], "hanzi": "血", "composition": ["⿰心水"] },
    "道": { "index": 135, "isDecomposable": true, "strokeCount": ["足", "処"], "hanzi": "道", "composition": ["⿰足処"] },
    "吁": { "index": 136, "isDecomposable": true, "strokeCount": ["五", "水"], "hanzi": "吁", "composition": ["⿱五水"] },
    "救": { "index": 137, "isDecomposable": true, "strokeCount": ["五", "人"], "hanzi": "救", "composition": ["⿱五人", "＊天"] },
    "従": { "index": 138, "isDecomposable": true, "strokeCount": ["将", "手"], "hanzi": "従", "composition": ["⿰将人"] },
    "从": { "index": 139, "isDecomposable": true, "strokeCount": ["王", "手"], "hanzi": "从", "composition": ["⿰王人"] },
    "奮": { "index": 140, "isDecomposable": true, "strokeCount": ["心", "火"], "hanzi": "奮", "composition": ["⿱心火"] },
    "酒": { "index": 141, "isDecomposable": true, "strokeCount": ["奮", "水"], "hanzi": "酒", "composition": ["⿰奮水"] },
    "煙": { "index": 142, "isDecomposable": true, "strokeCount": ["包", "火"], "hanzi": "煙", "composition": ["⿶包火"] },
    "味": { "index": 143, "isDecomposable": true, "strokeCount": ["五", "包"], "hanzi": "味", "composition": ["⿱五包"] },
    "甘": { "index": 144, "isDecomposable": true, "strokeCount": ["味", "上"], "hanzi": "甘", "composition": ["⿱上味"] },
    "混": { "index": 145, "isDecomposable": true, "strokeCount": ["包", "値"], "hanzi": "混", "composition": ["⿶包値"] },
    "御": { "index": 146, "isDecomposable": true, "strokeCount": ["大", "力"], "hanzi": "御", "composition": ["⿰大力"] },
    "労": { "index": 147, "isDecomposable": true, "strokeCount": ["人", "力"], "hanzi": "労", "composition": ["⿰人力"] },
    "能": { "index": 148, "isDecomposable": true, "strokeCount": ["力", "手"], "hanzi": "能", "composition": ["⿺力手"] },
    "後": { "index": 149, "isDecomposable": true, "strokeCount": ["背", "処"], "hanzi": "後", "composition": ["⿱背処"] },
    "素": { "index": 150, "isDecomposable": true, "strokeCount": ["始", "物"], "hanzi": "素", "composition": ["⿱始物"] },
    "踵": { "index": 151, "isDecomposable": true, "strokeCount": ["背", "足"], "hanzi": "踵", "composition": ["⿱背足"] },
    "文": { "index": 152, "isDecomposable": true, "strokeCount": ["筆", "連"], "hanzi": "文", "composition": ["⿰筆連"] },
    "聯": { "index": 153, "isDecomposable": true, "strokeCount": ["衣", "連"], "hanzi": "聯", "composition": ["⿰衣連"] },
    "鎖": { "index": 154, "isDecomposable": true, "strokeCount": ["連", "輪"], "hanzi": "鎖", "composition": ["⿹連輪"] },
    "祖": { "index": 155, "isDecomposable": true, "strokeCount": ["連", "人"], "hanzi": "祖", "composition": ["⿻連人"] },
    "多": { "index": 156, "isDecomposable": true, "strokeCount": ["人", "人"], "hanzi": "多", "composition": ["⿱人人"] },
    "極": { "index": 157, "isDecomposable": true, "strokeCount": ["物", "物"], "hanzi": "極", "composition": ["⿱物物"] },
    "増": { "index": 158, "isDecomposable": true, "strokeCount": ["足", "多"], "hanzi": "増", "composition": ["⿰足多"] },
    "笛": { "index": 159, "isDecomposable": true, "strokeCount": ["声", "筒"], "hanzi": "笛", "composition": ["⿰声筒"] },
    "笙": { "index": 160, "isDecomposable": true, "strokeCount": ["筒", "声"], "hanzi": "笙", "composition": ["⿰筒声"] },
    "正": { "index": 161, "isDecomposable": true, "strokeCount": ["直", "如"], "hanzi": "正", "composition": ["⿰直如"] },
    "長": { "index": 162, "isDecomposable": true, "strokeCount": ["大", "直"], "hanzi": "長", "composition": ["⿰大直"] },
    "謝": { "index": 163, "isDecomposable": true, "strokeCount": ["直", "為"], "hanzi": "謝", "composition": ["⿰直為"] },
    "歌": { "index": 164, "isDecomposable": true, "strokeCount": ["声", "声"], "hanzi": "歌", "composition": ["⿰声声"] },
    "寐": { "index": 165, "isDecomposable": true, "strokeCount": ["闇", "行"], "hanzi": "寐", "composition": ["⿰闇行"] },
    "恒": { "index": 166, "isDecomposable": true, "strokeCount": ["日", "五", "日"], "hanzi": "恒", "composition": ["⿳日五日"] },
    "立": { "index": 167, "isDecomposable": true, "strokeCount": ["人", "五"], "hanzi": "立", "composition": ["⿱人五"] },
    "享": { "index": 168, "isDecomposable": true, "strokeCount": ["筆", "果"], "hanzi": "享", "composition": ["⿱筆果"] },
    "隊": { "index": 169, "isDecomposable": true, "strokeCount": ["兵", "兵"], "hanzi": "隊", "composition": ["⿱兵兵"] },
    "軍": { "index": 170, "isDecomposable": true, "strokeCount": ["兵", "隊"], "hanzi": "軍", "composition": ["⿰兵隊", "⿰兵⿱兵兵"] },
    "止": { "index": 171, "isDecomposable": true, "strokeCount": ["五", "足"], "hanzi": "止", "composition": ["⿱五足"] },
    "冬": { "index": 172, "isDecomposable": true, "strokeCount": ["閉", "日"], "hanzi": "冬", "composition": ["⿱閉日"] },
    "石": { "index": 175, "isDecomposable": false, "strokeCount": 3, "hanzi": "石", "composition": ["⿱五己", "⿱少己"] },
    "如": { "index": 176, "isDecomposable": false, "strokeCount": 3, "hanzi": "如", "composition": ["⿸無＊力"] },
    "使": { "index": 177, "isDecomposable": true, "strokeCount": ["石", "手"], "hanzi": "使", "composition": ["⿱石手"] },
    "真": { "index": 178, "isDecomposable": true, "strokeCount": ["言", "石"], "hanzi": "真", "composition": ["⿱言石"] },
    "硬": { "index": 179, "isDecomposable": true, "strokeCount": ["石", "如"], "hanzi": "硬", "composition": ["⿰石如"] },
    "軟": { "index": 180, "isDecomposable": true, "strokeCount": ["棉", "如"], "hanzi": "軟", "composition": ["⿰棉如"] },
    "柔": { "index": 181, "isDecomposable": true, "strokeCount": ["糸", "如"], "hanzi": "柔", "composition": ["⿰糸如"] },
    "花": { "index": 183, "isDecomposable": false, "strokeCount": 5, "hanzi": "花", "composition": ["⿱四＊小"] },
    "蜜": { "index": 184, "isDecomposable": true, "strokeCount": ["花", "水"], "hanzi": "蜜", "composition": ["⿰花水"] },
    "春": { "index": 185, "isDecomposable": true, "strokeCount": ["花", "日"], "hanzi": "春", "composition": ["⿰花日"] },
    "雪": { "index": 186, "isDecomposable": true, "strokeCount": ["天", "花"], "hanzi": "雪", "composition": ["⿵天花"] },
    "机": { "index": 188, "isDecomposable": false, "strokeCount": 3, "hanzi": "机", "composition": ["⿱五＊儿", "＊兀"] },
    "席": { "index": 189, "isDecomposable": true, "strokeCount": ["人", "机"], "hanzi": "席", "composition": ["⿱人机"] },
    "箏": { "index": 190, "isDecomposable": true, "strokeCount": ["声", "机"], "hanzi": "箏", "composition": ["⿰声机"] },
    "座": { "index": 191, "isDecomposable": true, "strokeCount": ["無", "机"], "hanzi": "座", "composition": ["⿱無机"] },
    "再": { "index": 193, "isDecomposable": false, "strokeCount": 2, "hanzi": "再", "composition": ["＊ソ"] },
    "在": { "index": 194, "isDecomposable": true, "strokeCount": ["再", "処"], "hanzi": "在", "composition": ["⿱再処"] },
    "累": { "index": 195, "isDecomposable": true, "strokeCount": ["口", "再", "五"], "hanzi": "累", "composition": ["⿳口再五"] },
    "件": { "index": 196, "isDecomposable": true, "strokeCount": ["再", "物"], "hanzi": "件", "composition": ["⿱再物"] },
    "開": { "index": 198, "isDecomposable": false, "strokeCount": 2, "hanzi": "開", "composition": ["＊八", "＊ハ"] },
    "勿": { "index": 199, "isDecomposable": true, "strokeCount": ["開", "撃"], "hanzi": "勿", "composition": ["⿱開撃"] },
    "船": { "index": 200, "isDecomposable": true, "strokeCount": ["足", "開"], "hanzi": "船", "composition": ["⿱足開"] },
    "散": { "index": 201, "isDecomposable": true, "strokeCount": ["上", "開"], "hanzi": "散", "composition": ["⿱上開"] },
    "風": { "index": 203, "isDecomposable": false, "strokeCount": 2, "hanzi": "風", "composition": ["＊刀"] },
    "月": { "index": 204, "isDecomposable": true, "strokeCount": ["風", "五"], "hanzi": "月", "composition": ["⿱風五"] },
    "弓": { "index": 205, "isDecomposable": true, "strokeCount": ["風", "処"], "hanzi": "弓", "composition": ["⿻風処"] },
    "抗": { "index": 206, "isDecomposable": true, "strokeCount": ["弓", "力"], "hanzi": "抗", "composition": ["⿰弓力"] },
    "樽": { "index": 208, "isDecomposable": false, "strokeCount": 3.6, "hanzi": "樽", "composition": ["＊ㅂ"] },
    "鼓": { "index": 209, "isDecomposable": true, "strokeCount": ["声", "樽"], "hanzi": "鼓", "composition": ["⿸声樽"] },
    "皷": { "index": 210, "isDecomposable": true, "strokeCount": ["声", "樽"], "hanzi": "皷", "composition": ["⿰樽声"] },
    "深": { "index": 211, "isDecomposable": true, "strokeCount": ["五", "樽"], "hanzi": "深", "composition": ["⿱樽五", "＊브"] },
    "圧": { "index": 213, "isDecomposable": false, "strokeCount": 3, "hanzi": "圧", "composition": ["⿱橋五"] },
    "絵": { "index": 214, "isDecomposable": true, "strokeCount": ["筆", "圧"], "hanzi": "絵", "composition": ["⿱筆圧"] },
    "同": { "index": 216, "isDecomposable": false, "strokeCount": 7, "hanzi": "同", "composition": ["⿻⿱口口一", "＊串"] },
    "輩": { "index": 217, "isDecomposable": true, "strokeCount": ["同", "人"], "hanzi": "輩", "composition": ["⿱同人"] },
    "類": { "index": 218, "isDecomposable": true, "strokeCount": ["同", "等"], "hanzi": "類", "composition": ["⿰同等"] },
    "属": { "index": 219, "isDecomposable": true, "strokeCount": ["同", "多"], "hanzi": "属", "composition": ["⿰同多"] },
    "軸": { "index": 221, "isDecomposable": false, "strokeCount": 3, "hanzi": "軸", "composition": ["⿻処一", "＊キ"] },
    "北": { "index": 222, "isDecomposable": true, "strokeCount": ["星", "軸"], "hanzi": "北", "composition": ["⿺星軸"] },
    "翰": { "index": 223, "isDecomposable": true, "strokeCount": ["軸", "筆"], "hanzi": "翰", "composition": ["⿰軸筆"] },
    "橋": { "index": 226, "isDecomposable": false, "strokeCount": 2, "hanzi": "橋", "composition": ["＊冖"] },
    "車": { "index": 227, "isDecomposable": true, "strokeCount": ["橋", "輪"], "hanzi": "車", "composition": ["⿱橋輪"] },
    "冠": { "index": 228, "isDecomposable": true, "strokeCount": ["橋", "大", "軸"], "hanzi": "冠", "composition": ["⿱橋⿰大軸"] },
    "積": { "index": 229, "isDecomposable": false, "strokeCount": 5, "hanzi": "積", "composition": ["⿱橋圧"] },
    "族": { "index": 230, "isDecomposable": true, "strokeCount": ["人", "積"], "hanzi": "族", "composition": ["⿰人積"] },
    "＊ㄉ": { "index": 232, "isDecomposable": false, "strokeCount": 2, "hanzi": "＊ㄉ", "composition": ["⿹神少", "＊ㄉ"] },
    "亦": { "index": 233, "isDecomposable": true, "strokeCount": ["＊ㄉ", "五"], "hanzi": "亦", "composition": ["⿱％右風", "⿺⿹神少五"] },
    "乎": { "index": 234, "isDecomposable": true, "strokeCount": ["亦", "無"], "hanzi": "乎", "composition": ["⿻亦無"] },
    "地": { "index": 235, "isDecomposable": true, "strokeCount": ["＊ㄉ", "五"], "hanzi": "地", "composition": ["⿱⿹神少五"] },
    "平": { "index": 238, "isDecomposable": false, "strokeCount": 4, "hanzi": "平", "composition": ["⿴口一"] },
    "守": { "index": 239, "isDecomposable": true, "strokeCount": ["平", "人"], "hanzi": "守", "composition": ["⿰平人"] },
    "美": { "index": 240, "isDecomposable": true, "strokeCount": ["平", "上"], "hanzi": "美", "composition": ["⿱平上"] },
    "獣": { "index": 242, "isDecomposable": false, "strokeCount": 4, "hanzi": "獣", "composition": ["＊勿"] },
    "馬": { "index": 243, "isDecomposable": true, "strokeCount": ["処", "獣"], "hanzi": "馬", "composition": ["⿻処獣"] },
    "貓": { "index": 244, "isDecomposable": true, "strokeCount": ["閉", "獣"], "hanzi": "貓", "composition": ["⿱閉獣"] },
    "男": { "index": 246, "isDecomposable": false, "strokeCount": 4, "hanzi": "男", "composition": ["⿻人少"] },
    "父": { "index": 247, "isDecomposable": true, "strokeCount": ["上", "男"], "hanzi": "父", "composition": ["⿱上男"] },
    "㕮": { "index": 248, "isDecomposable": true, "strokeCount": ["声", "父"], "hanzi": "㕮", "composition": ["⿰声父"] },
    "周": { "index": 250, "isDecomposable": false, "strokeCount": 4, "hanzi": "周", "composition": ["⿻処二", "＊井"] },
    "近": { "index": 251, "isDecomposable": true, "strokeCount": ["足", "周"], "hanzi": "近", "composition": ["⿰足周"] },
    "広": { "index": 252, "isDecomposable": true, "strokeCount": ["周", "大"], "hanzi": "広", "composition": ["⿱周大"] },
    "草": { "index": 254, "isDecomposable": true, "strokeCount": ["毛", "五"], "hanzi": "草", "composition": ["⿱毛五"] },
    "種": { "index": 255, "isDecomposable": true, "strokeCount": ["五", "草"], "hanzi": "種", "composition": ["⿱五草"] },
    "茶": { "index": 256, "isDecomposable": true, "strokeCount": ["草", "水"], "hanzi": "茶", "composition": ["⿱草水"] },
    "小": { "index": 258, "isDecomposable": false, "strokeCount": 3, "hanzi": "小", "composition": ["⿱五六", "＊干"] },
    "挽": { "index": 259, "isDecomposable": true, "strokeCount": ["小", "為"], "hanzi": "挽", "composition": ["⿰小為"] },
    "短": { "index": 260, "isDecomposable": true, "strokeCount": ["小", "直"], "hanzi": "短", "composition": ["⿰小直"] },
    "銭": { "index": 262, "isDecomposable": false, "strokeCount": 4, "hanzi": "銭", "composition": ["⿱％六⿹衣無"] },
    "店": { "index": 263, "isDecomposable": true, "strokeCount": ["銭", "処"], "hanzi": "店", "composition": ["⿱銭処"] },
    "貧": { "index": 264, "isDecomposable": false, "strokeCount": 4.6, "hanzi": "貧", "composition": ["⿸％少銭"] },
    "左": { "index": 266, "isDecomposable": false, "strokeCount": 2, "hanzi": "左", "composition": ["⿻＊亅少"] },
    "倒": { "index": 267, "isDecomposable": true, "strokeCount": ["左", "閉"], "hanzi": "倒", "composition": ["⿰左閉"] },
    "而": { "index": 269, "isDecomposable": false, "strokeCount": 2, "hanzi": "而", "composition": ["⿻＊亅＊㇀"] },
    "即": { "index": 270, "isDecomposable": true, "strokeCount": ["而", "而"], "hanzi": "即", "composition": ["⿰而而"] },
    "木": { "index": 272, "isDecomposable": false, "strokeCount": 6, "hanzi": "木", "composition": ["⿻再＊木", "＊米"] },
    "竹": { "index": 273, "isDecomposable": true, "strokeCount": ["木", "筒"], "hanzi": "竹", "composition": ["⿰木筒"] },
    "竺": { "index": 274, "isDecomposable": true, "strokeCount": ["筒", "木"], "hanzi": "竺", "composition": ["⿰筒木"] },
    "色": { "index": 276, "isDecomposable": false, "strokeCount": 3, "hanzi": "色", "composition": ["⿰少九"] },
    "黒": { "index": 277, "isDecomposable": true, "strokeCount": ["色", "闇"], "hanzi": "黒", "composition": ["⿰色闇"] },
    "青": { "index": 278, "isDecomposable": true, "strokeCount": ["色", "水"], "hanzi": "青", "composition": ["⿰色水"] },
    "欽": { "index": 282, "isDecomposable": true, "strokeCount": ["無", "石"], "hanzi": "欽", "composition": ["⿸無石"] },
    "西": { "index": 284, "isDecomposable": false, "strokeCount": 5, "hanzi": "西", "composition": ["⿱％一日", "⿻橋大", "⿻六口", "＊由"] },
    "菓": { "index": 285, "isDecomposable": true, "strokeCount": ["五", "西"], "hanzi": "菓", "composition": ["⿱五西"] },
    "膠": { "index": 287, "isDecomposable": false, "strokeCount": 4.3, "hanzi": "膠", "composition": ["⿱⿻＊了再五"] },
    "脂": { "index": 288, "isDecomposable": true, "strokeCount": ["火", "膠"], "hanzi": "脂", "composition": ["⿰火膠"] },
    "骨": { "index": 290, "isDecomposable": false, "strokeCount": 5, "hanzi": "骨", "composition": ["⿻天軸"] },
    "肉": { "index": 291, "isDecomposable": true, "strokeCount": ["閉", "骨"], "hanzi": "肉", "composition": ["⿱閉骨"] },
    "彼": { "index": 293, "isDecomposable": false, "strokeCount": 3, "hanzi": "彼", "composition": ["＊己"] },
    "龍": { "index": 294, "isDecomposable": true, "strokeCount": ["七", "彼"], "hanzi": "龍", "composition": ["⿱七彼"] },
    "錘": { "index": 296, "isDecomposable": false, "strokeCount": 3.6, "hanzi": "錘", "composition": ["⿹力＊㇀"] },
    "禦": { "index": 297, "isDecomposable": true, "strokeCount": ["大", "錘"], "hanzi": "禦", "composition": ["⿰大錘"] },
    "目": { "index": 299, "isDecomposable": false, "strokeCount": 5, "hanzi": "目", "composition": ["⿴口二", "＊罒"] },
    "麗": { "index": 300, "isDecomposable": true, "strokeCount": ["目", "上"], "hanzi": "麗", "composition": ["⿱目上"] },
    "箱": { "index": 302, "isDecomposable": false, "strokeCount": 2, "hanzi": "箱", "composition": ["＊匸"] },
    "機": { "index": 303, "isDecomposable": true, "strokeCount": ["箱", "輪"], "hanzi": "機", "composition": ["⿷箱輪"] },
    "門": { "index": 305, "isDecomposable": false, "strokeCount": 2, "hanzi": "門", "composition": ["＊冂"] },
    "械": { "index": 306, "isDecomposable": true, "strokeCount": ["門", "輪"], "hanzi": "械", "composition": ["⿻門輪"] },
    "十": { "index": 308, "isDecomposable": false, "strokeCount": 1, "hanzi": "十", "composition": ["＊乙"] },
    "唯": { "index": 309, "isDecomposable": true, "strokeCount": ["十", "無"], "hanzi": "唯", "composition": ["⿻十無"] },
    "鳥": { "index": 311, "isDecomposable": false, "strokeCount": 2, "hanzi": "鳥", "composition": ["＊𠤎"] },
    "倉": { "index": 312, "isDecomposable": true, "strokeCount": ["閉", "鳥"], "hanzi": "倉", "composition": ["⿱閉鳥"] },
    "右": { "index": 314, "isDecomposable": false, "strokeCount": 2, "hanzi": "右", "composition": ["⿰一無", "＊ト", "＊卜"] },
    "横": { "index": 315, "isDecomposable": true, "strokeCount": ["左", "右"], "hanzi": "横", "composition": ["⿰左右"] },
    "虎": { "index": 317, "isDecomposable": false, "strokeCount": 4, "hanzi": "虎", "composition": ["⿱％五獣"] },
    "猫": { "index": 318, "isDecomposable": true, "strokeCount": ["閉", "虎"], "hanzi": "猫", "composition": ["⿱閉虎"] },
    "女": { "index": 320, "isDecomposable": false, "strokeCount": 4, "hanzi": "女", "composition": ["⿻少腹"] },
    "母": { "index": 321, "isDecomposable": true, "strokeCount": ["上", "女"], "hanzi": "母", "composition": ["⿱上女"] },
    "腹": { "index": 323, "isDecomposable": false, "strokeCount": 3, "hanzi": "腹", "composition": ["⿻五四", "＊丈"] },
    "前": { "index": 324, "isDecomposable": true, "strokeCount": ["腹", "処"], "hanzi": "前", "composition": ["⿱腹処"] },
    "巫": { "index": 326, "isDecomposable": false, "strokeCount": 5, "hanzi": "巫", "composition": ["⿻口之"] },
    "祭": { "index": 327, "isDecomposable": true, "strokeCount": ["巫", "火"], "hanzi": "祭", "composition": ["⿰巫火"] },
    "別": { "index": 329, "isDecomposable": false, "strokeCount": 4, "hanzi": "別", "composition": ["⿲＊㇀＊儿無"] },
    "裁": { "index": 330, "isDecomposable": true, "strokeCount": ["別", "物"], "hanzi": "裁", "composition": ["⿱別物"] },
    "米": { "index": 332, "isDecomposable": false, "strokeCount": 5, "hanzi": "米", "composition": ["＊氺"] },
    "刀": { "index": 333, "isDecomposable": false, "strokeCount": 3, "hanzi": "刀", "composition": ["⿰一六", "⿻上一", "＊丩"] },
    "秋": { "index": 334, "isDecomposable": true, "strokeCount": ["米", "刀"], "hanzi": "秋", "composition": ["⿰米刀"] },
    "神": { "index": 336, "isDecomposable": false, "strokeCount": 1, "hanzi": "神", "composition": ["＊㇉"] },
    "或": { "index": 337, "isDecomposable": false, "strokeCount": 3, "hanzi": "或", "composition": ["＊々"] },
    "位": { "index": 338, "isDecomposable": false, "strokeCount": 2, "hanzi": "位", "composition": ["＊乃"] },
    "字": { "index": 339, "isDecomposable": false, "strokeCount": 5, "hanzi": "字", "composition": ["⿱九⿻＊フ⿺＊乚無"] },
    "谷": { "index": 340, "isDecomposable": false, "strokeCount": 3, "hanzi": "谷", "composition": ["＊刄"] },
    "魚": { "index": 341, "isDecomposable": false, "strokeCount": 3, "hanzi": "魚", "composition": ["⿻＊レ⿺＊㇏少"] },
    "虫": { "index": 342, "isDecomposable": false, "strokeCount": 5, "hanzi": "虫", "composition": ["⿻包筆"] },
    "皇": { "index": 343, "isDecomposable": false, "strokeCount": 5, "hanzi": "皇", "composition": ["⿻橋軸", "⿻口六", "⿻＊中五"] },
    "貝": { "index": 344, "isDecomposable": false, "strokeCount": 3, "hanzi": "貝", "composition": ["＊彡"] },
    "函": { "index": 345, "isDecomposable": false, "strokeCount": 2, "hanzi": "函", "composition": ["＊コ"] },
    "中": { "index": 346, "isDecomposable": false, "strokeCount": 3, "hanzi": "中", "composition": ["⿱五上", "＊工", "＊エ"] },
    "外": { "index": 347, "isDecomposable": true, "strokeCount": 6, "hanzi": "外", "composition": ["⿰＊ㅌ＊ヨ", "⿰＊ㅌ＊크"] },
    "東": { "index": 348, "isDecomposable": false, "strokeCount": 5, "hanzi": "東", "composition": ["⿱％日一", "⿵橋軸", "⿻口六", "＊甲"] },
    "南": { "index": 349, "isDecomposable": false, "strokeCount": 7, "hanzi": "南", "composition": ["⿱％東大", "⿻東処", "⿻言大", "＊里"] },
    "九": { "index": 350, "isDecomposable": false, "strokeCount": 2, "hanzi": "九", "composition": ["⿱％五四", "＊ヌ", "＊又"] },
    "加": { "index": 351, "isDecomposable": false, "strokeCount": 3, "hanzi": "加", "composition": ["⿻五＊儿"] },
    "金": { "index": 352, "isDecomposable": false, "strokeCount": 5, "hanzi": "金", "composition": ["⿻再石"] },
    "夘": { "index": 353, "isDecomposable": true, "strokeCount": 5, "hanzi": "夘", "composition": ["⿰＊ㅌ右"] },
    "反": { "index": 354, "isDecomposable": false, "strokeCount": 1, "hanzi": "反", "composition": ["＊レ"] },
    "耳": { "index": 355, "isDecomposable": false, "strokeCount": 4, "hanzi": "耳", "composition": ["⿻少＊ヨ"] },
    "助": { "index": 356, "isDecomposable": false, "strokeCount": 4, "hanzi": "助", "composition": ["＊开"] },
    "豆": { "index": 357, "isDecomposable": false, "strokeCount": 8, "hanzi": "豆", "composition": ["⿳五⿻⿻再六再五", "⿳五⿻端再五"] },
    "嗅": { "index": 358, "isDecomposable": false, "strokeCount": 4, "hanzi": "嗅", "composition": ["⿻筆一"] },
    "傾": { "index": 359, "isDecomposable": false, "strokeCount": 2, "hanzi": "傾", "composition": ["＊厂"] },
    "震": { "index": 360, "isDecomposable": false, "strokeCount": 6, "hanzi": "震", "composition": ["⿲無＊中少"] },
    "端": { "index": 361, "isDecomposable": false, "strokeCount": 4, "hanzi": "端", "composition": ["⿻再六"] },
    "歪": { "index": 362, "isDecomposable": false, "strokeCount": ["＊フ", "十"], "hanzi": "歪", "composition": ["⿱＊フ十"] },
    "片": { "index": 363, "isDecomposable": false, "strokeCount": 4, "hanzi": "片", "composition": ["⿱五＊山"] },
    "針": { "index": 364, "isDecomposable": false, "strokeCount": 1, "hanzi": "針", "composition": ["＊亅"] },
    "氏": { "index": 365, "isDecomposable": true, "hanzi": "氏", "composition": ["⿱人圧"], "strokeCount": ["人", "圧"] },
    "閥": { "index": 366, "isDecomposable": true, "hanzi": "閥", "composition": ["⿰闇氏"], "strokeCount": ["闇", "氏"] },
    "纂": { "index": 367, "isDecomposable": true, "hanzi": "纂", "composition": ["⿰筆軸"], "strokeCount": ["筆", "軸"] },
    "穐": { "index": 368, "isDecomposable": true, "hanzi": "穐", "composition": ["⿰黍刀"], "strokeCount": ["黍", "刀"] },
    "通": { "index": 369, "isDecomposable": true, "hanzi": "通", "composition": ["⿱足処"], "strokeCount": ["足", "処"] },
    "啌": { "index": 370, "isDecomposable": true, "hanzi": "啌", "composition": ["⿰声美"], "strokeCount": ["声", "美"] },
    "哇": { "index": 371, "isDecomposable": true, "hanzi": "哇", "composition": ["⿰声而"], "strokeCount": ["声", "而"] },
    "浬": { "index": 372, "isDecomposable": true, "hanzi": "浬", "composition": ["⿲二花貓"], "strokeCount": ["二", "花", "貓"] },
    "刻": { "index": 373, "isDecomposable": true, "hanzi": "刻", "composition": ["⿱日片"], "strokeCount": ["日", "片"] },
    "羅": { "index": 374, "isDecomposable": true, "hanzi": "羅", "composition": ["⿴口軸"], "strokeCount": ["口", "軸"] },
    "聚": { "index": 375, "isDecomposable": true, "hanzi": "聚", "composition": ["⿱口⿰口口"], "strokeCount": ["口", "口", "口"] },
    "叛": { "index": 376, "isDecomposable": false, "hanzi": "叛", "composition": ["＊オ"], "strokeCount": 3 },
    "科": { "index": 377, "isDecomposable": true, "hanzi": "科", "composition": ["⿰心内"], "strokeCount": ["心", "内"] },
    "吏": { "index": 378, "isDecomposable": true, "hanzi": "吏", "composition": ["⿰人官"], "strokeCount": ["人", "官"] },
    "宦": { "index": 379, "isDecomposable": true, "hanzi": "宦", "composition": ["⿱官人"], "strokeCount": ["官", "人"] },
    "僚": { "index": 380, "isDecomposable": true, "hanzi": "僚", "composition": ["⿱官翰"], "strokeCount": ["官", "翰"] },
    "健": { "index": 381, "isDecomposable": true, "hanzi": "健", "composition": ["⿰人善"], "strokeCount": ["人", "善"] },
    "兄": { "index": 382, "isDecomposable": true, "hanzi": "兄", "composition": ["⿰⿱腹上輩"], "strokeCount": ["腹", "上", "輩"] },
    "赤": { "index": 383, "isDecomposable": true, "hanzi": "赤", "composition": ["⿱火色"], "strokeCount": ["火", "色"] },
    "百": { "index": 384, "isDecomposable": true, "hanzi": "百", "composition": ["⿱大物"], "strokeCount": ["大", "物"] },
    "佰": { "index": 385, "isDecomposable": true, "hanzi": "佰", "composition": ["⿱物大"], "strokeCount": ["物", "大"] },
    "失": { "index": 386, "isDecomposable": true, "hanzi": "失", "composition": ["⿻手無"], "strokeCount": ["手", "無"] },
    "網": { "index": 387, "isDecomposable": false, "hanzi": "網", "composition": ["⿻処三"], "strokeCount": 5 },
    "顫": { "index": 388, "isDecomposable": true, "hanzi": "顫", "composition": ["⿱震処"], "strokeCount": ["震", "処"] },
    "振": { "index": 389, "isDecomposable": true, "hanzi": "振", "composition": ["⿲無書少"], "strokeCount": ["無", "書", "少"] },
    "帽": { "index": 390, "isDecomposable": true, "hanzi": "帽", "composition": ["⿱橋長"], "strokeCount": ["橋", "長"] },
    "瑪": { "index": 391, "isDecomposable": false, "hanzi": "瑪", "composition": ["＊ㄞ", "⿱五＊ㄌ", "⿱五⿻神少"], "strokeCount": 3 },
    "産": { "index": 392, "isDecomposable": true, "hanzi": "産", "composition": ["⿴包足"], "strokeCount": ["包", "足"] },
    "須": { "index": 393, "isDecomposable": true, "hanzi": "須", "composition": ["⿰黍虫"], "strokeCount": ["黍", "虫"] },
    "刺": { "index": 394, "isDecomposable": false, "hanzi": "刺", "composition": ["⿻処＊乚"], "strokeCount": 3 },
    "民": { "index": 395, "isDecomposable": false, "hanzi": "民", "composition": ["⿳＊夫無無"], "strokeCount": 6 },
    "育": { "index": 396, "isDecomposable": true, "hanzi": "育", "composition": ["⿰足大"], "strokeCount": ["足", "大"] },
    "呻": { "index": 397, "isDecomposable": true, "hanzi": "呻", "composition": ["⿰声疲"], "strokeCount": ["声", "疲"] },
    "可": { "index": 398, "isDecomposable": true, "hanzi": "可", "composition": ["⿰力力"], "strokeCount": ["力", "力"] },
    "卵": { "index": 399, "isDecomposable": true, "hanzi": "卵", "composition": ["⿱橋七"], "strokeCount": ["橋", "七"] },
    "淮": { "index": 400, "isDecomposable": true, "hanzi": "淮", "composition": ["⿰人卵"], "strokeCount": ["人", "卵"] },
    "球": { "index": 401, "isDecomposable": true, "hanzi": "球", "composition": ["⿱橋己"], "strokeCount": ["橋", "己"] },
    "遠": { "index": 402, "isDecomposable": true, "hanzi": "遠", "composition": ["⿰周耒"], "strokeCount": ["周", "耒"] },
    "蛋": { "index": 403, "isDecomposable": true, "hanzi": "蛋", "composition": ["⿴口心"], "strokeCount": ["口", "心"] },
    "付": { "index": 404, "isDecomposable": true, "hanzi": "付", "composition": ["⿱五与"], "strokeCount": ["五", "与"] },
    "激": { "index": 405, "isDecomposable": true, "hanzi": "激", "composition": ["⿱九手"], "strokeCount": ["九", "手"] },
    "迷": { "index": 406, "isDecomposable": true, "hanzi": "迷", "composition": ["⿱失処"], "strokeCount": ["失", "処"] },
    "寒": { "index": 407, "isDecomposable": true, "hanzi": "寒", "composition": ["⿱日小"], "strokeCount": ["日", "小"] },
    "穴": { "index": 408, "isDecomposable": true, "hanzi": "穴", "composition": ["⿱口刺"], "strokeCount": ["口", "刺"] },
    "軽": { "index": 409, "isDecomposable": true, "hanzi": "軽", "composition": ["⿴錘無"], "strokeCount": ["錘", "無"] },
    "杯": { "index": 410, "isDecomposable": true, "hanzi": "杯", "composition": ["⿱包上"], "strokeCount": ["包", "上"] },
    "思": { "index": 411, "isDecomposable": true, "hanzi": "思", "composition": ["⿰心心"], "strokeCount": ["心", "心"] },
    "帝": { "index": 412, "isDecomposable": true, "hanzi": "帝", "composition": ["⿱王机"], "strokeCount": ["王", "机"] },
    "顔": { "index": 413, "isDecomposable": true, "hanzi": "顔", "composition": ["⿴口⿻再上"], "strokeCount": ["口", "再", "上"] },
    "白": { "index": 414, "isDecomposable": true, "hanzi": "白", "composition": ["⿺色光"], "strokeCount": ["色", "光"] },
    "普": { "index": 415, "isDecomposable": true, "hanzi": "普", "composition": ["⿰貝鳥"], "strokeCount": ["貝", "鳥"] },
    "型": { "index": 416, "isDecomposable": true, "hanzi": "型", "composition": ["⿱圧口"], "strokeCount": ["圧", "口"] },
    "醇": { "index": 417, "isDecomposable": true, "hanzi": "醇", "composition": ["⿰⿱火心水"], "strokeCount": ["火", "心", "水"] },
    "毛": { "index": 418, "isDecomposable": false, "strokeCount": 3, "hanzi": "毛", "composition": ["＊ツ"] },
    "牛": { "index": 419, "isDecomposable": true, "hanzi": "牛", "composition": ["⿰少谷", "＊匁"], "strokeCount": ["少", "谷"] },
    "牡": { "index": 420, "isDecomposable": true, "hanzi": "牡", "composition": ["⿰五牛", "⿰＊フ谷"], "strokeCount": ["＊フ", "谷"] },
    "羊": { "index": 421, "isDecomposable": true, "hanzi": "羊", "composition": ["⿱毛獣"], "strokeCount": ["毛", "獣"] },
    "羚": { "index": 422, "isDecomposable": true, "hanzi": "羚", "composition": ["⿱毛虎"], "strokeCount": ["毛", "虎"] },
    "犬": { "index": 423, "isDecomposable": false, "hanzi": "犬", "composition": ["⿱⿰少五八"], "strokeCount": ["少", "五", "八"] },
    "咍": { "index": 424, "isDecomposable": true, "hanzi": "咍", "composition": ["⿰声力"], "strokeCount": ["声", "力"] },
    "子": { "index": 425, "isDecomposable": true, "hanzi": "子", "composition": ["⿱口中"], "strokeCount": ["口", "中"] },
    "壁": { "index": 426, "isDecomposable": true, "hanzi": "壁", "composition": ["⿰圧処"], "strokeCount": ["圧", "処"] },
    "巻": { "index": 427, "isDecomposable": true, "hanzi": "巻", "composition": ["⿴口衣"], "strokeCount": ["口", "衣"] },
    "常": { "index": 428, "isDecomposable": false, "hanzi": "常", "composition": ["⿱少一", "＊イ"], "strokeCount": ["少", "一"] },
    "槍": { "index": 429, "isDecomposable": true, "hanzi": "槍", "composition": ["⿰常刀"], "strokeCount": ["常", "刀"] },
    "鑓": { "index": 430, "isDecomposable": true, "hanzi": "鑓", "composition": ["⿰常兵"], "strokeCount": ["常", "等"] },
    "躍": { "index": 431, "isDecomposable": true, "hanzi": "躍", "composition": ["⿱火足"], "strokeCount": ["火", "足"] },
    "凹": { "index": 432, "isDecomposable": true, "hanzi": "凹", "composition": ["⿱再五"], "strokeCount": ["再", "五"] },
    "斧": { "index": 433, "isDecomposable": true, "hanzi": "斧", "composition": ["⿱金足"], "strokeCount": ["金", "足"] },
    "質": { "index": 434, "isDecomposable": true, "hanzi": "質", "composition": ["⿱四下"], "strokeCount": ["四", "下"] },
    "毎": { "index": 435, "isDecomposable": true, "hanzi": "毎", "composition": ["⿱開二"], "strokeCount": ["開", "二"] },
    "形": { "index": 436, "isDecomposable": true, "hanzi": "形", "composition": ["⿴口四"], "strokeCount": ["口", "四"] },
    "急": { "index": 437, "isDecomposable": true, "hanzi": "急", "composition": ["⿰足馬"], "strokeCount": ["足", "馬"] },
    "穏": { "index": 438, "isDecomposable": true, "hanzi": "穏", "composition": ["⿰静心"], "strokeCount": ["静", "心"] },
    "必": { "index": 439, "isDecomposable": true, "hanzi": "必", "composition": ["⿰米⿻虫五"], "strokeCount": ["米", "虫", "五"] },
    "囁": { "index": 440, "isDecomposable": true, "hanzi": "囁", "composition": ["⿱言小"], "strokeCount": ["言", "小"] },
    "叫": { "index": 441, "isDecomposable": true, "hanzi": "叫", "composition": ["⿱大言"], "strokeCount": ["大", "言"] },
    "鶏": { "index": 442, "isDecomposable": true, "hanzi": "鶏", "composition": ["⿱四鳥"], "strokeCount": ["四", "鳥"] },
    "胸": { "index": 443, "isDecomposable": true, "hanzi": "胸", "composition": ["⿻人再"], "strokeCount": ["人", "再"] },
    "怖": { "index": 444, "isDecomposable": true, "hanzi": "怖", "composition": ["⿰心寒"], "strokeCount": ["心", "寒"] },
    "遊": { "index": 445, "isDecomposable": true, "hanzi": "遊", "composition": ["⿱草手", "⿱毛撃"], "strokeCount": ["草", "手"] },
    "決": { "index": 446, "isDecomposable": true, "strokeCount": ["一", "手"], "hanzi": "決", "composition": ["⿰一手"] },
    "汪": { "index": 447, "isDecomposable": true, "strokeCount": ["声", "犬"], "hanzi": "汪", "composition": ["⿰声犬"] },
    "硫": { "index": 448, "isDecomposable": true, "hanzi": "硫", "composition": ["⿱火石"], "strokeCount": ["火", "石"] },
    "俐": { "index": 449, "isDecomposable": true, "hanzi": "俐", "composition": ["⿱石火"], "strokeCount": ["石", "火"] },
    "榎": { "index": 450, "isDecomposable": true, "hanzi": "榎", "composition": ["⿰木夏"], "strokeCount": ["木", "夏"] },
    "株": { "index": 451, "isDecomposable": true, "hanzi": "株", "composition": ["⿰木赤"], "strokeCount": ["木", "赤"] },
    "織": { "index": 452, "isDecomposable": true, "hanzi": "織", "composition": ["⿰糸机"], "strokeCount": ["糸", "机"] },
    "村": { "index": 453, "isDecomposable": true, "hanzi": "村", "composition": ["⿲人家人"], "strokeCount": ["人", "家", "人"] },
    "頬": { "index": 454, "isDecomposable": false, "hanzi": "頬", "composition": ["⿺＊乚四"], "strokeCount": 3 },
    "体": { "index": 455, "isDecomposable": false, "hanzi": "体", "composition": ["⿵門四", "＊冈"], "strokeCount": ["門", "四"] },
    "引": { "index": 456, "isDecomposable": true, "hanzi": "引", "composition": ["⿱糸手"], "strokeCount": ["糸", "手"] },
    "犛": { "index": 457, "isDecomposable": true, "hanzi": "犛", "composition": ["⿱毛牛"], "strokeCount": ["毛", "牛"] },
    "牲": { "index": 458, "isDecomposable": true, "hanzi": "牲", "composition": ["⿱毛牡"], "strokeCount": ["毛", "牡"] },
    "溜": { "index": 459, "isDecomposable": true, "hanzi": "溜", "composition": ["⿱凹水"], "strokeCount": ["凹", "水"] },
    "泉": { "index": 460, "isDecomposable": true, "hanzi": "泉", "composition": ["⿱始水"], "strokeCount": ["始", "水"] },
    "玉": { "index": 461, "isDecomposable": false, "hanzi": "玉", "composition": ["⿱毛己", "⿱％毛石"], "strokeCount": 5 },
    "叉": { "index": 462, "isDecomposable": false, "hanzi": "叉", "composition": ["⿻刀少"], "strokeCount": 3.6 },
    "飛": { "index": 463, "isDecomposable": true, "hanzi": "飛", "composition": ["⿱鳥開"], "strokeCount": ["鳥", "開"] },
    "鍋": { "index": 464, "isDecomposable": true, "hanzi": "鍋", "composition": ["⿱己火"], "strokeCount": ["己", "火"] },
    "蟲": { "index": 465, "isDecomposable": true, "hanzi": "蟲", "composition": ["⿻五虫"], "strokeCount": ["五", "虫"] },
    "矢": { "index": 466, "isDecomposable": true, "hanzi": "矢", "composition": ["⿰槍弓"], "strokeCount": ["槍", "弓"] },
    "玄": { "index": 467, "isDecomposable": true, "hanzi": "玄", "composition": ["⿰闇色"], "strokeCount": ["闇", "色"] },
    "慥": { "index": 468, "isDecomposable": true, "hanzi": "慥", "composition": ["⿱石大"], "strokeCount": ["石", "大"] },
    "釘": { "index": 469, "isDecomposable": true, "hanzi": "釘", "composition": ["⿱⿰少五針"], "strokeCount": ["少", "五", "針"] },
    "槌": { "index": 470, "isDecomposable": true, "hanzi": "槌", "composition": ["⿱⿰少五錘"], "strokeCount": ["少", "五", "錘"] },
    "檸": { "index": 471, "isDecomposable": true, "hanzi": "檸", "composition": ["⿰木術"], "strokeCount": ["木", "術"] },
    "妙": { "index": 472, "isDecomposable": true, "hanzi": "妙", "composition": ["⿰貝⿻鳥無"], "strokeCount": ["貝", "鳥", "無"] },
    "哦": { "index": 473, "isDecomposable": true, "hanzi": "哦", "composition": ["⿰声平"], "strokeCount": ["声", "平"] },
    "涙": { "index": 474, "isDecomposable": true, "hanzi": "涙", "composition": ["⿱目水"], "strokeCount": ["目", "水"] },
    "悖": { "index": 475, "isDecomposable": true, "hanzi": "悖", "composition": ["⿰心字"], "strokeCount": ["心", "字"] },
    "順": { "index": 476, "isDecomposable": true, "hanzi": "順", "composition": ["⿱位五"], "strokeCount": ["位", "五"] },
    "嗚": { "index": 477, "isDecomposable": true, "hanzi": "嗚", "composition": ["⿰声心"], "strokeCount": ["声", "心"] },
    "黍": { "index": 478, "isDecomposable": true, "hanzi": "黍", "composition": ["⿱五米"], "strokeCount": ["五", "米"] },
    "乾": { "index": 479, "isDecomposable": true, "hanzi": "乾", "composition": ["⿰小水"], "strokeCount": ["小", "水"] },
    "湿": { "index": 480, "isDecomposable": true, "hanzi": "湿", "composition": ["⿰大水"], "strokeCount": ["大", "水"] },
    "待": { "index": 481, "isDecomposable": true, "hanzi": "待", "composition": ["⿱人処"], "strokeCount": ["人", "処"] },
    "搾": { "index": 482, "isDecomposable": true, "hanzi": "搾", "composition": ["⿱圧種"], "strokeCount": ["圧", "種"] },
    "窄": { "index": 483, "isDecomposable": true, "hanzi": "窄", "composition": ["⿱圧草"], "strokeCount": ["圧", "草"] },
    "万": { "index": 484, "isDecomposable": true, "hanzi": "万", "composition": ["⿱大大", "＊圭"], "strokeCount": ["大", "大"] },
    "癒": { "index": 485, "isDecomposable": true, "hanzi": "癒", "composition": ["⿱傷手"], "strokeCount": ["傷", "手"] },
    "叮": { "index": 486, "isDecomposable": true, "hanzi": "叮", "composition": ["⿰車力"], "strokeCount": ["車", "力"] },
    "斥": { "index": 487, "isDecomposable": true, "hanzi": "斥", "composition": ["⿵門口"], "strokeCount": ["門", "口"] },
    "半": { "index": 488, "isDecomposable": true, "hanzi": "半", "composition": ["⿰刀刀"], "strokeCount": ["刀", "刀"] },
    "逆": { "index": 489, "isDecomposable": true, "hanzi": "逆", "composition": ["⿱再下"], "strokeCount": ["再", "下"] },
    "鹽": { "index": 490, "isDecomposable": true, "hanzi": "鹽", "composition": ["⿰石海"], "strokeCount": ["石", "海"] },
    "塩": { "index": 491, "isDecomposable": true, "hanzi": "塩", "composition": ["⿰海火"], "strokeCount": ["海", "火"] },
    "苦": { "index": 492, "isDecomposable": true, "hanzi": "苦", "composition": ["⿱草味"], "strokeCount": ["草", "味"] },
    "渋": { "index": 493, "isDecomposable": true, "hanzi": "渋", "composition": ["⿱種味"], "strokeCount": ["種", "味"] },
    "辣": { "index": 494, "isDecomposable": true, "hanzi": "辣", "composition": ["⿰味火"], "strokeCount": ["味", "火"] },
    "節": { "index": 495, "isDecomposable": false, "hanzi": "節", "composition": ["⿰＊く＊く"], "strokeCount": 2 },
    "田": { "index": 496, "isDecomposable": true, "hanzi": "田", "composition": ["⿴口米"], "strokeCount": ["口", "米"] },
    "土": { "index": 497, "isDecomposable": true, "hanzi": "土", "composition": ["⿱米五"], "strokeCount": ["米", "五"] },
    "旱": { "index": 498, "isDecomposable": true, "hanzi": "旱", "composition": ["⿰日⿱日日"], "strokeCount": ["日", "日", "日"] },
    "氾": { "index": 499, "isDecomposable": true, "hanzi": "氾", "composition": ["⿱水圧"], "strokeCount": ["水", "圧"] },
    "腰": { "index": 500, "isDecomposable": true, "hanzi": "腰", "composition": ["⿴口己"], "strokeCount": ["口", "己"] },
    "像": { "index": 501, "isDecomposable": true, "hanzi": "像", "composition": ["⿵門値"], "strokeCount": ["門", "値"] },
    "鹵": { "index": 502, "isDecomposable": true, "hanzi": "鹵", "composition": ["⿰石味"], "strokeCount": ["石", "味"] },
    "匁": { "index": 503, "isDecomposable": true, "hanzi": "匁", "composition": ["⿰直錘"], "strokeCount": ["直", "錘"] },
    "飢": { "index": 504, "isDecomposable": true, "hanzi": "飢", "composition": ["⿰少黍"], "strokeCount": ["少", "黍"] },
    "遅": { "index": 505, "isDecomposable": true, "hanzi": "遅", "composition": ["⿰足牛"], "strokeCount": ["足", "牛"] },
    "支": { "index": 506, "isDecomposable": true, "hanzi": "支", "composition": ["⿱口机"], "strokeCount": ["口", "机"] },
    "奉": { "index": 507, "isDecomposable": false, "hanzi": "奉", "composition": ["⿱口＊廾"], "strokeCount": 6 },
    "捧": { "index": 508, "isDecomposable": true, "hanzi": "捧", "composition": ["⿱口術"], "strokeCount": ["口", "術"] },
    "贄": { "index": 509, "isDecomposable": true, "hanzi": "贄", "composition": ["⿵天与"], "strokeCount": ["天", "与"] },
    "鍬": { "index": 510, "isDecomposable": true, "hanzi": "鍬", "composition": ["⿻函六"], "strokeCount": ["函", "六"] },
    "謗": { "index": 511, "isDecomposable": true, "hanzi": "謗", "composition": ["⿸傾言"], "strokeCount": ["傾", "言"] },
    "佞": { "index": 512, "isDecomposable": true, "hanzi": "佞", "composition": ["⿸傾人"], "strokeCount": ["傾", "人"] },
    "麺": { "index": 513, "isDecomposable": true, "hanzi": "麺", "composition": ["⿰米糸"], "strokeCount": ["米", "糸"] },
    "餅": { "index": 514, "isDecomposable": true, "hanzi": "餅", "composition": ["⿰米平"], "strokeCount": ["米", "平"] },
    "招": { "index": 515, "isDecomposable": true, "hanzi": "招", "composition": ["⿰人引"], "strokeCount": ["人", "引"] },
    "賢": { "index": 516, "isDecomposable": true, "hanzi": "賢", "composition": ["⿱上思"], "strokeCount": ["上", "思"] },
    "緑": { "index": 517, "isDecomposable": true, "hanzi": "緑", "composition": ["⿱色草"], "strokeCount": ["色", "草"] },
    "虹": { "index": 518, "isDecomposable": true, "hanzi": "虹", "composition": ["⿱天橋"], "strokeCount": ["天", "橋"] },
    "雷": { "index": 519, "isDecomposable": true, "hanzi": "雷", "composition": ["⿵天神"], "strokeCount": ["天", "神"] },
    "呉": { "index": 520, "isDecomposable": true, "hanzi": "呉", "composition": ["⿴口草"], "strokeCount": ["口", "草"] },
    "＊フ": { "index": 521, "isDecomposable": false, "strokeCount": 1, "hanzi": "＊フ", "composition": ["＊フ"] },
    "麦": { "index": 522, "isDecomposable": true, "hanzi": "麦", "composition": ["⿻端五"], "strokeCount": ["端", "五"] },
    "棆": { "index": 523, "isDecomposable": true, "hanzi": "棆", "composition": ["⿰木輪"], "strokeCount": ["木", "輪"] },
    "眉": { "index": 524, "isDecomposable": true, "hanzi": "眉", "composition": ["⿱五目"], "strokeCount": ["五", "目"] },
    "残": { "index": 525, "isDecomposable": true, "hanzi": "残", "composition": ["⿱人十"], "strokeCount": ["人", "十"] },
    "豚": { "index": 526, "isDecomposable": true, "hanzi": "豚", "composition": ["⿱獣水"], "strokeCount": ["獣", "水"] },
    "豕": { "index": 527, "isDecomposable": true, "hanzi": "豕", "composition": ["⿲之之之"], "strokeCount": ["之", "之", "之"] },
};
